### ISSUE TITLE
update with new ARIA 1.1 roles/attributes

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/html-aria#1]
from https://github.com/webspecs/html-aria/issues/23 (now dead)

**Comment by stevefaulkner** [comment]
email to PF last year asking for info about implementation status:
https://lists.w3.org/Archives/Public/public-pfwg/2015Jul/0077.html

**Comment by dylanb** [comment]
@stevefaulkner the GitHub URL for the issue is no longer valid

**Comment by stevefaulkner** [comment]
@dylanb noted - it was only a placeholder note anyways

**Comment by stevefaulkner** [comment]
change log for aria 1.1 https://w3c.github.io/aria/aria/aria.html#changelog

**Comment by stevefaulkner** [comment]
fixed
