### ISSUE TITLE
img with alt text should allow the doc-cover role

### ISSUE THREAD

**Issue by rdeltour** [w3c/html-aria#100]
see the [`doc-cover` definition in DPUB-ARIA](https://www.w3.org/TR/dpub-aria-1.0/#doc-cover)

**Comment by stevefaulkner** [comment]
@rdeltour currently `img` with non empty `alt `allows **any role**, except `presentation/none`, which includes any `dpub` role.

**Comment by rdeltour** [comment]
Doh 😳. I must have mixed up this line with the one for `img` with empty `alt`. Sorry!
