### ISSUE TITLE
allow doc-* link roles on area with href

### ISSUE THREAD

**Issue by rdeltour** [w3c/html-aria#101]
consider allowing the following roles on `area` with `href`:

- [`doc-backlink`](https://www.w3.org/TR/dpub-aria-1.0/#doc-backlink)
- [`doc-biblioref`](https://www.w3.org/TR/dpub-aria-1.0/#doc-biblioref)
- [`doc-glossref`](https://www.w3.org/TR/dpub-aria-1.0/#doc-glossref)
- [`doc-noteref`](https://www.w3.org/TR/dpub-aria-1.0/#doc-noteref)

**Comment by scottaohara** [comment]
@rdeltour it looks like this was already merged into the spec, but in reviewing it again today I have a question about `doc-noteref`.

Should that role be allowed on a `<a href>` or is it meant to not act as a link?  The example in the ARIA DPub spec uses it on an `<a>` without an `href`, which either seems like an oversight with the example in the DPub spec, or I need to allow it on `<a>` and not `<a href>` here.

Thanks

**Comment by rdeltour** [comment]
> Should that role be allowed on a `<a href>` or is it meant to not act as a link?

As far as I'm were it's clearly meant to be used as links (and it subclasses the `link` role), so yes I think it's an oversight in DPUB ARIA’s example 30.
Typically the noteref would be used both as a link to the actual note, plus also as an anchor for a backlink, but I don't think I've ever seen it used as an anchor only.

Pinging @mattgarrish (who's the DPUB ARIA editor and master of all EPUB/DPUB specs 😊) for confirmation.

**Comment by mattgarrish** [comment]
> so yes I think it's an oversight in DPUB ARIA’s example 30.

Yes, that's definitely a mistake in the example. An inactive note reference is somewhat useless; it's not something I'd expect to see done in the wild. I've opened an issue in the dpub aria tracker.

**Comment by scottaohara** [comment]
thanks @mattgarrish 

Then looks like this issue is good to close, because all those roles are in the Spec now.
