### ISSUE TITLE
Broken links to github repo at top of spec

### ISSUE THREAD

**Issue by mcking65** [w3c/html-aria#112]
At the top of the spec, there are links for file a bug, commit history, and pull requests. They are broken because they do not include the repo name.

**Comment by stevefaulkner** [comment]
thanks @mcking65, @siusin @ylafon where are the URLs for this set?


>    Participate: 
>    GitHub w3c/html-aria 
>     File a bug 
>     Commit history 
>     Pull requests

**Comment by siusin** [comment]
It's in the respecConfig setting, the "`github`" link requires a "`/`" in the end.

**Comment by stevefaulkner** [comment]
fixed by https://github.com/w3c/html-aria/commit/542c9203601492da0a60b917d1e725ab43a26dea
