### ISSUE TITLE
The concept of "descendant" does not consider Shadow DOM

### ISSUE THREAD

**Issue by kasperisager** [w3c/html-aria#116]
Consider the following example:

```html
<div id="host">
  <footer>I'm the first footer!</footer>
</div>

<script>
  const host = document.querySelector("#host");
  const root = host.attachShadow({ mode: "open" });

  root.innerHTML = `
    <main>
      <slot></slot>
      <footer>I'm the second footer!</footer>
    </main>
  `;
</script>
```

What should the role of the first footer be? Both footers are rendered as children of `<main>` so I would expect neither to have an implicit role. In Chrome, for example, this is however not the case as the first footer is assigned a role of `contentinfo`:

![image](https://user-images.githubusercontent.com/1174718/43965089-a6dd47ee-9cbe-11e8-98cf-3b1f84c58b12.png)

Given that the concept of "descendant" is never really defined in "ARIA in HTML" I do see how an ambiguity like this would arise.

**Comment by stevefaulkner** [comment]
@kasperisager closing here as aria in html does not define what roles should/must be exposed by user agents, this is defined in HTML Accessibility API Mappings 1.0 see [footer](https://w3c.github.io/html-aam/#el-footer) . Your issue may be better raised there?
