### ISSUE TITLE
header/footer implicit role needs to include ancestor element's implied role (not just element type)

### ISSUE THREAD

**Issue by carmacleod** [w3c/html-aria#117]
The [doc conformance table](http://w3c.github.io/html-aria/#docconformance) entry for `<header>` says:
> If not a descendant of an article, aside, main, nav - (changed) or section element role=banner, otherwise No corresponding role

Similarly, the entry for `<footer>` says:
> If not a descendant of an article, aside, main, nav - (changed) or section element role=contentinfo, otherwise No corresponding role

I think the **implied role** for each of the listed elements should also be taken into consideration when determining whether the descendant header or footer has an implicit role, i.e. role=article, complimentary, main, navigation or region.

For example, this could be written (for both `<header>` and `<footer>`) as:
> If not a descendant of an article, aside, main, nav (changed) or section element or an element with role=article, complimentary, main, navigation or region ...

(note that I also deleted the extraneous - hyphen).

**Comment by cpandhi** [comment]
+1 to the above needed calrification.
