### ISSUE TITLE
Link element with href with implied link role should allow ARIA* attributes

### ISSUE THREAD

**Issue by cpandhi** [w3c/html-aria#119]
The [HTML 5.2 spec ](https://www.w3.org/TR/html5/document-metadata.html#the-link-element)says for the `<link>` element 
Allowed ARIA role attribute values:
    None 
Allowed ARIA state and property attributes:
    None 
According to the ARIA in HTML l[atest document conformance table ](https://w3c.github.io/html-aria/#docconformance)
link element with a href | role=link | No role or aria* attributes

As it has an implied link role, should it not be allowed global aria-* attributes and any aria-* attributes applicable to the implied role? or should it say no implied role? 

Which spec is correct? can you please clarify?

**Comment by scottaohara** [comment]
Hi @cpandhi 
The [HTML 5.3 draft](http://w3c.github.io/html/document-metadata.html#the-link-element) has already updated this information to align with the ARIA in HTML spec.

**Comment by cpandhi** [comment]
Thanks @scottaohara 
 As i see it they still conflict.
The HTML 5.3 draft
Allowed ARIA role attribute values:
    None 
Allowed ARIA state and property attributes:
    None 
Which conflicts with ARIA in HTML latest document conformance table which says `<link>` with href has implied role of link (which further implies all global aria attributes and implied role attributes should be allowed.
link element with a href | role=link | No role or aria* attributes

**Comment by scottaohara** [comment]
`a` elements and `link` elements (with `href`s) are both types of "links", which is why they both fall under this role.

However, they serve very different purposes being elements that belong in the `body` and `head` respectively.  What would the benefit be to allow global ARIA attributes on an element (`link`) that would not be accessed by users?

**Comment by cpandhi** [comment]
@scottaohara thanks again. 
Understand your point.
