### ISSUE TITLE
aria-owns / aria-controls on <button> / role=button

### ISSUE THREAD

**Issue by M13iriam** [w3c/html-aria#124]
Hi there,

I find the W3C ARIA in HTML (Working Draft 14 December 2018) very helpful. But I have come across a question I could not clarify, even with intensive research. 

For buttons only the aria attributes aria-expanded and aria-pressed are listed as supported properties. 
As I am in the process of making toolbar buttons accessible and my company is also using a framework, the structure is as follows:

I have a link with role=button and aria-owns a div with a ul (role=menu and its children with role=menuitem), coming from the framework. My accessibility tool shows me the aria-owns attribute for role=button as invalid. And it is indeed not listed in the specification. But the acutal ul is elsewhere in the dom so I consider aria-owns justified.

As I researched different examples of similar interactive elements I noticed, that many use aria-controls which is also not specified as supported property for buttons.

Thank you very much for clarification.

And as follow-up:
The attributes' description of aria-owns contains a cross reference to aria-controls and vice versa. 
A clarification whether those two are exclusive or combinable would also be much appreciated.
As in my case above, I think aria-owns is justified for moving the ul under the controlling button-element, but as I understood aria-owns, it merely influences the accesibility tree. Shouldn't aria-controls, aria-expanded and aria-haspopup also be used to further specify the control element?

**Comment by mcking65** [comment]
First, very, very important. I strongly doubt you want to put aria-owns on a button, especially pointing to a UL. That is the same thing as writing:

~~~
<button>
  <ul>
    <li>item 1</li>
    <li>item 2</li>
    <!-- etc. -->
  </ul>
</button>
~~~

What aria-owns does is sort of like telling the browser to lie to the assistive technology about the structure of the DOM by rearranging the accessibility tree. There are times when that is extremely helpful.

It's really hard to imagine a situation where aria-owns referencing a list on a button would be a good idea. Buttons are labeled by their content, and a list is not going to make a good label. If you were to override with aria-label on the button, then the list would completely disappear!! So, please do not put aria-owns on a button referencing a list.

Now for your question about the properties supported by button ... 

The description of the table you are referencing in the ARIA in HTML document says the first 4 columns are informative, not normative. The normative specification is ARIA 1.1. The ARIA in HTML table lists the supported properties, but not the additional inherited properties. The [ARIA 1.1 specification of button](https://www.w3.org/TR/wai-aria-1.1/#button) also includes the following 21 inherrited properties:

* aria-atomic
* aria-busy (state)
* aria-controls
* aria-current (state)
* aria-describedby
* aria-details
* aria-disabled (state)
* aria-dropeffect
* aria-errormessage
* aria-flowto
* aria-grabbed (state)
* aria-haspopup
* aria-hidden (state)
* aria-invalid (state)
* aria-keyshortcuts
* aria-label
* aria-labelledby
* aria-live
* aria-owns
* aria-relevant
* aria-roledescription

We are right now working on a new toolbar example for the ARIA Authoring Practices, and it includes a button that opens a menu. It is not yet merged into master, but likely will be next week. For now, you can find it here:
https://raw.githack.com/w3c/aria-practices/issue541-toolbar-redesign/examples/toolbar/toolbar.html

Once merged, it will be in the editor's draft:
http://w3c.github.io/aria-practices/

Then, after Jan 21, you will find it in our third release of the ARIA Authoring Practices here:
https://www.w3.org/TR/wai-aria-practices-1.1/


I have a feeling that you might also find the editor menubar example useful:
https://www.w3.org/TR/wai-aria-practices-1.1/examples/menubar/menubar-2/menubar-2.html

And, if you haven't already done so, please read the [Read Me First section](https://www.w3.org/TR/wai-aria-practices-1.1/#read_me_first) of the APG.

**Comment by mcking65** [comment]
Oh, and your accessibility tool might be complaining because the UL may contain some interactive content, and that is not a legal descendant of the button element.

**Comment by M13iriam** [comment]
**Thank you very much for the fast answer and detailed information and all the links provided!**

In parts this has cleared some questions and in parts I got confused regarding other points. 

I have tested my button with JAWS and it follows all the described behaviour of the menubar-example, except for the home- and end-button one. 

**Here is the simplified structure as provided by the framework:**

```html
<div role="toolbar">
  <a role="button" aria-haspopup="true" aria-owns="menuId">
    <span>
      Button Name
    </span>
  </a>
</div>

[...]

<div id="menuId" role="menu" aria-hidden="true/false" aria-expanded="false/true">
  <a role="menuitemcheckbox" aria-checked="true/false">
    <span>
      First Item
    </span>
  </a>
  <a role="menuitemcheckbox" aria-checked="true/false">
    <span>
      Second Item
    </span>
  </a>
</div>
```

**JAWS reads the Button as follows:**
Toolbar readonly, Button Name button-menu, press space to activate the menu, then navigate with arrow keys.
**on space/enter pressed:**
space/enter, menu, First(Second) Item (not) checked, one(two) of two, to move through items press up or down arrow.

It also works to type the first char of an element's name to select the menuitem beginning with that char and you can leave the menu by pressing escape.

**So, the questions that arose are the following:**
- Do I need to add the functionality for the home&end-button? 
- Or is Enter/Space to activate the button, up/down for navigating the items, char x for selecting one item x, esc for leaving the menu enough?
- Do I forcefully have to change the aria-attributes (especially aria-owns) provided by the framework, even if it works?
- Why is aria-owns not recommended on role='button' eventhough it is inherrited, too, as is aria-controls and the list is not read as label but the `<span>` is?

If I remove aria-owns, the functionality of navigating the menuitems with the up/down arrows gets lost and instead a navigation of the toolbar items is triggered. So presumably a lot would have to be overwritten of how the framework works at the moment if aria-owns has to be removed.

**Comment by scottaohara** [comment]
As Matt already noted, `aria-owns` is meant to indicate a parent/child relationship that doesn't exist in the markup, but should. A menu should not be a child of a button, but rather controlled by the button.

The ARIA specification, and the links Matt provided to the APG would be very helpful to follow in correctly implementing the menu patterns you posted.
