### ISSUE TITLE
Allow <ul role=list>

### ISSUE THREAD

**Issue by zcorpan** [w3c/html-aria#125]
See 
https://github.com/validator/validator/issues/741
https://bugs.webkit.org/show_bug.cgi?id=170179

**Comment by scottaohara** [comment]
This should extend to `ol` as well.

Though normally not necessary, possibly a note/exception could be added due to Webkit's behavior here.

**Comment by stevefaulkner** [comment]
Note, the addition of an implied role is a _should not_ not a _must not_, so the addition is not ruled out. If you would like to suggest some addition note for this role I can add.

**Comment by scottaohara** [comment]
word smith away:

"Note that some UAs may suppress a list's semantics if its list markers have been removed. Authors MAY add `role="list"` to reinstate the `list` role, in such situations."

**Comment by zcorpan** [comment]
#165 uses a normative keyword in a non-normative context (in a note). That is not good.

I also think this is more complicated than it needs to be -- we can just straight allow this role on lists, and explain in a note why this case is different from the general rule.

**Comment by stevefaulkner** [comment]
@scottaohara @zcorpan is right about use of "MAY", my bad, suggest that you change to "can", this leaves the overall "should not" in effect. As we do not want to encourage authors to add unnecessarily.
