### ISSUE TITLE
Should colgroup HTML element allow aria global properties?

### ISSUE THREAD

**Issue by cpandhi** [w3c/html-aria#127]
As per the [document conformance table](https://www.w3.org/TR/html-aria/#docconformance) there is a mention that ARIA global states and properties can be used on any HTML element.
Then why some elements like colgroup, base, head do not mention global aria-* attributes in the 3rd column? Does that mean that global aria-* attributes are not allowed or is it typo / editorial that needs fixing.

**Comment by scottaohara** [comment]
@cpandhi could you please reference the text you're referring to?  Is it the following, or are you referring to something else?
> Each language feature (element or attribute) in a cell in the first column implies the ARIA semantics (any role, states, and properties) given in the cell in the second column of the same row. The third cell in each row defines which ARIA role values and aria-* attributes which MAY be used.

**Comment by stevefaulkner** [comment]
@cpandhi attributes and roles are forbidden where they don't make sense to use. If the element is not represented in the accessibility tree (for example). `<colgroup>` elements are not represented in the accessibility tree and therefore ARIA attributes are not allowed on them.

**Comment by cpandhi** [comment]
@stevefaulkner thanks that makes perfect sense. Looks like the HTML 5.2 spec [https://www.w3.org/TR/html52/tabular-data.html#the-colgroup-element](url) then needs update to the information on such elements as well to match.

**Comment by scottaohara** [comment]
@cpandhi note [updated in 5.3 draft](https://www.w3.org/TR/html53/tabular-data.html#the-colgroup-element)

**Comment by cpandhi** [comment]
Perfect thanks ya'll.
