### ISSUE TITLE
Mismatch between ARIA and HTML on required radio groups

### ISSUE THREAD

**Issue by dylanb** [w3c/html-aria#13]
The HTML 5 spec does not allow a required attribute on a fieldset element.

The HTML 5 spec allows a required attribute on a input of type radio

The ARIA spec does not allow aria-required="true" on a radio role

The ARIA spec does allow aria-required on a group role

This makes it difficult for developers to grok the mapping between HTML and ARIA.

With the understanding that ARIA is intended to be bigger than just HTML, is there any good reason for this discrepancy?

**Comment by stevefaulkner** [comment]
@dylanb 

> The HTML 5 spec allows a required attribute on a input of type radio
> 
> The ARIA spec does not allow aria-required="true" on a radio role

it does:

> Use the aria-required attribute on any element that is allowed the required attribute in HTML5. MUST NOT be set to false if the required attribute is set. 
> https://www.w3.org/TR/html-aria/#attr-required

**Comment by stevefaulkner** [comment]
closing as there is not an actionable issue for this spec.
