### ISSUE TITLE
should be fixed the table of "Document conformance requirements for use of ARIA attributes in HTML"

### ISSUE THREAD

**Issue by mtrootyy** [w3c/html-aria#140]
The following elements should be added to row of the table of "Document conformance requirements for use of ARIA attributes in HTML" (https://w3c.github.io/html-aria/#implicit)

- [x] hgroup (ref: https://html.spec.whatwg.org/multipage/sections.html#the-hgroup-element)
- [x] i (ref: https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-i-element)
- [x] rp (ref: https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-rp-element)
- [x] slot (ref: https://html.spec.whatwg.org/multipage/scripting.html#the-slot-element)
- [x] menu (ref: https://html.spec.whatwg.org/multipage/grouping-content.html#the-menu-element)
- [x] li element whose parent is menu element (ref: https://html.spec.whatwg.org/multipage/grouping-content.html#the-li-element)
- [x] area without href attribute (ref: https://html.spec.whatwg.org/multipage/image-maps.html#the-area-element:the-area-element-6)
- [x] img without alt attribute (ref: https://html.spec.whatwg.org/multipage/images.html#unknown-images)
- [x] input type=datetime-local (ref: https://html.spec.whatwg.org/multipage/input.html#local-date-and-time-state-(type=datetime-local))
- [x] autonomous custom element (ref: https://html.spec.whatwg.org/multipage/custom-elements.html#autonomous-custom-element)

　

The following elements should be removed from the table of "Document conformance requirements for use of ARIA attributes in HTML" (https://w3c.github.io/html-aria/#implicit)
- [x] input type=datetime (because "type=datetime" does not exist in input element of HTML Living Standard)
- [x] menu type = context (because "type=context" does not exist in menu element of HTML Living Standard)
- [x] menuitem type=command (because menuitem element does not exist in HTML Living Standard)
- [x] menuitem type=checkbox (because menuitem element does not exist in HTML Living Standard)
- [x] menuitem type=radio (because menuitem element does not exist in HTML Living Standard)
- [x] button type=menu (because "type=menu" does not exist in button element of HTML Living Standard)

**Comment by stevefaulkner** [comment]
@sideshowbarker like the `<a>` no `href` is the `<area>` no `href` undistinguishable from from the validator point of view?

**Comment by sideshowbarker** [comment]
> @sideshowbarker like the `<a>` no `href` is the `<area>` no `href` undistinguishable from from the validator point of view?

Actually, support for separate ARIA handling for `<a>` no `href` was added to the checker back in March; see 6b427ee. So if wanted to do something similar for `<area>` no `href`, yeah, that would be possible.
