### ISSUE TITLE
id references for a and href have gone missing

### ISSUE THREAD

**Issue by pgrucza** [w3c/html-aria#142]
The editor's draft seems to be missing a couple of references for a with and without href.

a element with a href currently:
`<a><code>a</code></a> element with a <code>href</code>`

possible change to:
`<a><code>a</code></a> element with a <a data-cite="html/links.html#attr-hyperlink-href"><code>href</code></a>`

a element without a href currently:
`<code>a</code></a> element without a <code>href</code>`

possible change to:
`<a><code>a</code></a> element without a <a data-cite="html/links.html#attr-hyperlink-href"><code>href</code></a>`

**Comment by marcoscaceres** [comment]
@pgrucza quick pr? 🙇‍♂️
