### ISSUE TITLE
HTML Standard inserted into empty links

### ISSUE THREAD

**Issue by pgrucza** [w3c/html-aria#145]
In index.html the table, ARIA Roles, States and Properties, has four instances of empty `<a>` elements.  Previously these were not shown to users but with recent changes they now all show a link labelled "HTML Standard". The empty links can be found in the following rows:

- button Descendant restrictions`<a data-cite="html/dom.html#phrasing-content-2"></a>`
- checkbox Descendant restrictions `<a data-cite="html/dom.html#phrasing-content-2"></a>`
- dialog Kind of content `<a data-cite="html/dom.html#interactive-content"></a>`
- heading Descendant restrictions `<a data-cite="html/dom.html#phrasing-content-2"></a>`

Should each of these be given a proper name or should they be removed?

**Comment by marcoscaceres** [comment]
If the empty anchors serve no useful purpose, we should remove them. Any idea why they were originally there?

**Comment by pgrucza** [comment]
The empty link references seem to have been added as part of a draft change for the issue, define nesting conformance requirements for roles when used in HTML #54
