### ISSUE TITLE
Review role descendant restrictions table column 

### ISSUE THREAD

**Issue by scottaohara** [w3c/html-aria#156]
Per the [comments in PR #155](https://github.com/w3c/html-aria/pull/155#pullrequestreview-258161242) there should be a review of the role descendant restrictions and ensure that all necessary restrictions are up to date.  Again, noting the conversation from the referenced PR.

**Comment by scottaohara** [comment]
@stevefaulkner did your recent work / closing of  #256 essentially make this issue moot?

**Comment by stevefaulkner** [comment]
@scottaohara yes
