### ISSUE TITLE
Specification status report for TPAC 2019

### ISSUE THREAD

**Issue by LJWatson** [w3c/html-aria#160]
Please can you respond to this comment with a brief specifications status report for the WebApps meeting at TPAC. The report should address the following:
* What progress has your spec made in the last 12 months?
* Is anything blocking your spec from moving to CR?
* If yes, what is your plan to unblock it and do you need any help?
* What do you want to achieve for your spec in the next two days (of breakout sessions)?

We're tracking these status reports in [WebApps issue #19](https://github.com/w3c/webappswg/issues/19)

Thanks.

**Comment by stevefaulkner** [comment]
@LJWatson 
What progress has your spec made in the last 12 months?
- 37 commits made and 14 bugs closed.
Is anything blocking your spec from moving to CR?
- lack of multiple implementations
If yes, what is your plan to unblock it and do you need any help?
- work with a11y tool vendors to get more than 1 implementation
What do you want to achieve for your spec in the next two days (of breakout sessions)?
N/A not attending TPAC

**Comment by marcoscaceres** [comment]
Hi @stevefaulkner, @scottaohara, 

> 37 commits made and 14 bugs closed.

That's great! Anything that stands out from those that we you  are most excited about? Would like to share with the larger community about progress.  

> lack of multiple implementations

Is  this in browsers? Are there particular parts  that are higher priority where we could try to involve implementers a bit more?
