### ISSUE TITLE
Ambiguous sentence regarding interactive content

### ISSUE THREAD

**Issue by dbrusilovsky** [w3c/html-aria#163]
Under [Allowed ARIA roles, states and properties](https://www.w3.org/TR/html-aria/#allowed-aria-roles-states-and-properties) I noticed the following sentence:

> For example, an element with `role=button` is interactive content and therefore cannot contain interactive content descendants.

While it's true that an element with `role=button` cannot contain interactive content, the sentence implies that the *reason* this is true is that interactive content cannot contain interactive content, which is not true. The `details` and `label` tags are both interactive content which are allowed to contain interactive content. 

I feel this sentence is therefore misleading.

**Comment by stevefaulkner** [comment]
@dbrusilovsky agreed will update thanks
