### ISSUE TITLE
aside element and role doc-dedication

### ISSUE THREAD

**Issue by pkra** [w3c/html-aria#173]
Currently, role=doc-dedication is not permitted on an aside element, cf. https://www.w3.org/TR/html-aria/#aside

I'm wondering why this is, especially given how, e.g., role=doc-example is allowed on an aside element.

**Comment by pkra** [comment]
For the record, I had first posted w3c/aria#918 which was both confused and confusing.

**Comment by scottaohara** [comment]
hey again @pkra ;)

seems quite reasonable that this'd be allowed, so PR has been made.  Thanks

**Comment by pkra** [comment]
Thanks, @scottaohara!  And thank you for making a PR. 

Sorry again for the confusion on my end.
