### ISSUE TITLE
Provide example/guidance on using aria-disabled on a w/out href

### ISSUE THREAD

**Issue by scottaohara** [w3c/html-aria#186]
if authors really want to disable links, they can instead do `<a role=link aria-disabled=true>` as removing the `href` rather than jumping through all the hoops to try and suppress the various ways one can interact with a link.

**Comment by scottaohara** [comment]
this update should be accompanied by an example

**Comment by scottaohara** [comment]
this issue will be partially resolved when #262 is merged.  an example what to do instead (e.g., an `<a>` w/out `href` used with `aria-disabled=true`) would need to be made to close this issue.

**Comment by stes-acc** [comment]
Have you checked possible issues with validators using

`<a role=link aria-disabled=true>`

with respect to role redundancy warnings?

**Comment by scottaohara** [comment]
`<a>` without `href` allows for any role.  `<a>` without `href` is not supposed to be exposed as a `link`, so there's no redundancy here.

**Comment by scottaohara** [comment]
closing as this work will be picked up in #259
