### ISSUE TITLE
Add new ARIA roles

### ISSUE THREAD

**Issue by scottaohara** [w3c/html-aria#200]
The following roles are new in ARIA 1.2 and need to be added to the spec

- [x] `blockquote` => `<blockquote>`
- [x] `caption` => `<caption>` and <s>`<figcaption>`</s>
- [x] `code` => `<code>`
- [x] `definition` => revised, no HTML element match
- [x] `deletion` => `<del>`
- [x] `emphasis` => `<em>`
- [ ] `generic` => `<div>`, `<span>`, & other user facing elements with no meaningful ARIA role.
- [x] `insertion` => `<ins>`
- [x] `meter` => `<meter>`
- [x] `paragraph` => `<p>`
- [x] `strong` => `<strong>`
- [x] `subscript` => `<sub>`
- [x] `superscript` => `<sup>`
- [x] `term` => `<dfn>` and not `<dt>`
- [x] `time` => `<time>`

(removed `label` and `legend` these likely won't be added anymore)

## ARIA 1.3 roles
- `mark` => `<mark>` 
- `suggestion` => no HTML element 
- `comment` => no HTML element 

The following roles may be changed in their naming
- `associationlist` => `<dl>` 
- `associationlistkey` => `<dt>` 
- `associationlistvalue` => `<dd>`

**Comment by mtrootyy** [comment]
- [ ] `paragraph` => `<p>`

**Comment by masi** [comment]
The above list of new roles for 1.2 includes roles in the draft that did not made it into the final version:

- definition
- emphasis
- label
- legend
- strong
- term

**Comment by stevefaulkner** [comment]
> The above list of new roles for 1.2 includes roles in the draft that did not made it into the final version

Is there a final version? I thought 1.2 was still in progress. The [latest editors draft](https://w3c.github.io/aria/) includes some of the above

**Comment by masi** [comment]
Stupid me! Of course 1.2 is still a WD. I am ahead of time that's all :)

They made it into the mentioned version. Now ARIA really re-implements HTML in roles.

**Comment by scottaohara** [comment]
Adding allowed aria-* attributes and allowed roles labels as the updated implicit roles may require some changes for certain elements.

**Comment by WW3** [comment]
Different roles to distinguish between ordered and unordered lists?

**Comment by scottaohara** [comment]
@WW3 that wouldn't be defined here.  See https://github.com/w3c/aria/issues/961 instead
