### ISSUE TITLE
footer & text input missing a few words after "...applicable to the allowed"

### ISSUE THREAD

**Issue by carmacleod** [w3c/html-aria#207]
The following sentence is used in the rules table for global & applicable attributes:
> Global aria-* attributes and any aria-* attributes applicable to the allowed roles and implied role (if any).

For [footer](https://w3c.github.io/html-aria/#el-footer), this sentence is missing " roles and implied role (if any)":
> Global aria-* attributes and any aria-* attributes applicable to the allowed.

Also, for [input type=text](https://w3c.github.io/html-aria/#el-input-text) this sentence is missing " and implied role (if any)":
> Global aria-* attributes and any aria-* attributes applicable to the allowed roles.

Aside: Personally, I would just delete " and implied role (if any)" from all the places, because isn't the implied role (if any) also an allowed role?

Edit: I can provide a PR if my Aside question is answered... :)

**Comment by carmacleod** [comment]
Also, [input type=radio](https://w3c.github.io/html-aria/#el-input-radio) says:
> Global aria-* attributes and any aria-* attributes applicable to the menuitemradio role.

Which is missing "attributes applicable to radio role".

So this sentence should either be:
> Global aria-* attributes and any aria-* attributes applicable to the radio or menuitemradio role.

or it should be:
> Global aria-* attributes and any aria-* attributes applicable to the allowed roles and implied role (if any).

or (personal choice, given my Aside question, above) it should simply be:
> Global aria-* attributes and any aria-* attributes applicable to the allowed roles.

**Comment by scottaohara** [comment]
@stevefaulkner, i like @carmacleod's suggestion of
>Global aria-* attributes and any aria-* attributes applicable to the allowed roles.

that sound ok to you?

**Comment by scottaohara** [comment]
edit to the above suggestion:
>Global aria-* attributes and any aria-* attributes applicable to the exposed role.
