### ISSUE TITLE
Combobox required to own textbox

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/html-aria#21]
I noticed this problem when working on Axe. Elements with a role of combobox are required to own two elements: listbox and textbox. (https://www.w3.org/TR/wai-aria-1.1/#combobox). Though if you look at the example of the combobox, there is no element with a textbox role. Instead a type=text input element is given the role=combobox. How exactly should this be implemented? Should the example in this case also contain a textbox?

**Comment by stevefaulkner** [comment]
HI @WilcoFiers, I think this issue should be raised against the ARIA spec, as [ARIA in HTML](https://www.w3.org/TR/html-aria/) only describes conformance requirements for use of ARIA in HTML. If you agree please close this bug and file as appropriate.

Anyway this may help clarify the issue you raised; from the [ARIA 1.1 spec](https://www.w3.org/TR/wai-aria-1.1/#mustContain):

> When multiple roles are specified as required owned elements for a role, at least one instance of one required owned element is expected. This specification **does not require an instance of each of the listed owned roles**. [emphasis mine]

**Comment by WilcoFiers** [comment]
Cheers!
