### ISSUE TITLE
Consider revising allowed roles for heading elements

### ISSUE THREAD

**Issue by scottaohara** [w3c/html-aria#215]
Consider allowing additional roles (especially with new ARIA 1.2 roles coming).

Or, disallow `role=tab`, as it's a bit odd to allow that interactive role but not other roles.

per #102

**Comment by stevefaulkner** [comment]
@scottaohara When initially discussed (way back) I wanted to disallow as much as possible, the only use case that was raised was for headings used as tabs. Unless there is good reason and uses in the wild why would we want to allow more?

**Comment by scottaohara** [comment]
I tend to agree. But I wanted to at least consider if some of the roles coming in aria 1.2 could apply. 

Just keeping an open mind for a bit :)

**Comment by scottaohara** [comment]
Circling back on this... i think in the spirit of the original intent for limiting roles here if we allow any new roles it should be `blockquote` and `paragraph`.  If only to allow for mitigating against misuse of headings, and allowing a more appropriate role to be used... which is why I assume the `presentation` and `none` roles are also allowed, but obviously those don't fallback to more meaningful roles.

If you disagree, @stevefaulkner, then let's just shut this one down :)
