### ISSUE TITLE
Add Internationalization Considerations section

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/html-aria#220]
There may or may not be any internationalization concerns with the spec, but we should make sure to have an "Internationalization Considerations" section stating that we've taken i18n into consideration. Of course, if there are things that should be considered, we should add them there :)

We will also ask the i18n WG to review the spec to see if they have any feedback for us.

This is part of w3c/webappswg#25

**Comment by pkra** [comment]
https://w3c.github.io/aria/#translatable-states-and-properties covers some of this. 

@marcoscaceres are there guidelines (besides the title of the section) to make those sections more recognizable/consistent across specs?

**Comment by marcoscaceres** [comment]
I might let @r12a and the @w3c/i18n-wg answer that, as they are the authoritative source of how this should be done.

**Comment by scottaohara** [comment]
Upon review, and per [other comments made about adding such a section](https://github.com/w3c/IntersectionObserver/issues/415#issuecomment-698363306), we are going to close this issue. As with the [privacy & security section](https://w3c.github.io/html-aria/#priv-sec), this spec does not define the features of ARIA or HTML so there would be no concerns to call out here that wouldn't be more appropriate to call out in those specs where the features are defined.
