### ISSUE TITLE
Incorrect or confusing description of aria-required usage

### ISSUE THREAD

**Issue by Haprog** [w3c/html-aria#225]
See this table: https://www.w3.org/TR/html-aria/#document-conformance-requirements-for-use-of-aria-attributes-in-html

Here's a screenshot with some unrelated rows deleted for easily showing the column headers with few related rows:
![image](https://user-images.githubusercontent.com/75155/77167724-39d85c80-6abf-11ea-809f-6c399b64ee66.png)

The highlighted piece of text in the third column seem to be contradicting since the second column defines that `aria-required="true"` should not be used on element with a `required` attribute.

Compare this text with the third column of the "disabled" and "readonly" rows which are more logical.

Should this instead say (similarly to disabled and readonly):
> Use the `required` attribute on any element that is [allowed the `required` attribute](https://html.spec.whatwg.org/multipage/input.html#attr-input-required) in HTML.
>
> Only use the `aria-required` attribute for elements that are **not allowed** to have a `required` attribute in HTML."

Or is the `aria-required` a more special case compared to `aria-disabled` or `aria-readonly`?

**Comment by scottaohara** [comment]
closed by #262
