### ISSUE TITLE
aria-checked shouldn't be a required for an element role=switch when the switch is created with checkbox

### ISSUE THREAD

**Issue by mpnkhan** [w3c/html-aria#227]
There are multiple ways to create a switch component, div, span, button. We can also use native element like checkbox with role=switch.  Here is an example with switch component with checkboxes http://hcm-sample.surge.sh.  W3C docs say aria-checked is a required attribute for switch role. Validators like axe throw an error even though the checked state is exposed by browsers and read by screen readers. 
aria-checked shouldn't be an required attribute for <input type="checkbox role="switch""> 

<img width="1311" alt="Screen Shot 2020-05-07 at 11 11 20 AM" src="https://user-images.githubusercontent.com/2254656/81371253-01471d80-9115-11ea-8f56-74494d1c7d03.png">

**Comment by JAWS-test** [comment]
I suspect that for a switch based on a checkbox the requirement "required attribute: aria-checked" is automatically met because each checkbox has implicitly aria-checked=true or aria-checked=false (see https://w3c.github.io/html-aam/#el-input-checkbox). 

So the error is probably caused by validators like axe and a ticket should be created there

**Comment by scottaohara** [comment]
This is not an issue with this document, but rather with validators as @JAWS-test mentions.

As ARIA in HTML already mentions:
>Note: the HTML `checked` attribute may be used instead of the `aria-checked` attribute for `menuitemcheckbox`, `option` or `switch` when used on `type=checkbox`. 

If you are finding axe is throwing an error, then you can [file a bug against that tool](https://github.com/dequelabs/axe-core).

**Comment by mpnkhan** [comment]
Nope, the bug is about the document https://w3c.github.io/html-aria/#index-aria-switch  and https://www.w3.org/TR/wai-aria-1.1/#switch which says aria-checked is  required attribute. 
"The aria-checked attribute of a switch indicates whether the input is on (true) or off (false). The mixed value is invalid, and user agents MUST treat a mixed value as equivalent to false for this role.".  
The document should explicitly state that aria-checked shouldn't be needed for checkbox elements. 
Did i misunderstood?

**Comment by mpnkhan** [comment]
Also filed https://github.com/dequelabs/axe-core/issues/2225 .
