### ISSUE TITLE
No default role for input[type="password"]

### ISSUE THREAD

**Issue by jschfflr** [w3c/html-aria#238]
According to this [spec](https://www.w3.org/TR/html-aria/#docconformance) an input field of type password does not have a default role but according to the [Accessibility API Mappings](https://www.w3.org/TR/html-aam-1.0/#x4-4-html-element-role-mappings) all other accessibility apis have a mapping for it. Is there a specific reason for not defining a default role for this case?

**Comment by stevefaulkner** [comment]
@jschfflr 

>all other accessibility apis have a mapping for it. Is there a specific reason for not defining a default role for this case?

The reason is that the platform mappings are not consistent. For example, Ia2 is Role: ROLE_SYSTEM_TEXT while ATK is Role: ATK_ROLE_PASSWORD_TEXT.
