### ISSUE TITLE
other aria-* attributes which should not be allowed on HTML elements

### ISSUE THREAD

**Issue by scottaohara** [w3c/html-aria#241]
for starters, aria-checked should not be used on a native `input type=checkbox/radio`  It's both unnecessary, and if out of alignment, the native HTML state will largely win (as it should) over the aria attribute (except in chrome where this rule is not implemented properly).

However, that's even more reason to make an explicit rule for this, so that developers are encouraged not to use the attribute unnecessarily and find themselves in a misalignment situation.

Similarly, should look at should not-ing `aria-selected` on `option`

**Comment by mitchellevan** [comment]
I agree. Similarly, `aria-multiselect` should not be used on `<select multiple>`

**Comment by scottaohara** [comment]
closed by #262
