### ISSUE TITLE
checkbox and switch should allow aria-expanded

### ISSUE THREAD

**Issue by mitchellevan** [w3c/html-aria#251]
### Current

https://w3c.github.io/html-aria/#allowed-aria-roles-states-and-properties

* The checkbox role does not allow aria-expanded.
* The switch role does not allow aria-expanded.

However, the ARIA Editor's Draft allows them.

* https://w3c.github.io/aria/#checkbox
* https://w3c.github.io/aria/#switch

### Proposed

Add aria-expanded in the Supported Properties column for checkbox and switch.

**Comment by scottaohara** [comment]
This, among many other updates pertaining to alignment with ARIA 1.2, will be addressed in PR #198

**Comment by mitchellevan** [comment]
@scottaohara Feel free to leave this issue open for tracking, or close it if it's sufficiently tracked in #192 or elsewhere

**Comment by scottaohara** [comment]
it's a good reminder / allows others to know aria 1.2 updates are coming.  going to leave it open.

**Comment by scottaohara** [comment]
this section of the table has been removed, so this issue is no longer relevant.
