### ISSUE TITLE
Using ARIA despite implicit HTML semantics

### ISSUE THREAD

**Issue by JAWS-test** [w3c/html-aria#254]
https://www.w3.org/TR/html-aria/#rules-wd:

> Web developers MAY use the ARIA role ... , except where these ... are equal to the implicit ARIA semantics of a given HTML element.

> It is NOT RECOMMENDED for web developers to set the ARIA role and aria-* attributes to values that match the implicit ARIA semantics defined in the table

Perhaps the rules, which are correct in themselves, could be accompanied by a note that it is sometimes very useful to repeat the implicit role per ARIA, e.g., for
* Tables and lists, since screen readers use their own heuristics when an HTML table or HTML list is output as a table or list.
* header and footer, since header and footer have an implicit ARIA role only in a specific context of body.

**Comment by masi** [comment]
And allow aria-hidden together with hidden. The latter will a) be overriden by CSS and b) may be changed with JavaScript.

**Comment by scottaohara** [comment]
@JAWS-test  section two has the note
>While setting an ARIA role and/or aria-* attribute that matches the implicit ARIA semantics is NOT RECOMMENDED, in some situations explicitly setting these attributes can be helpful. For instance, in user agents which lack specific implicit semantics. 

So the spec already acknowledges that there are instances where a not recommended approach may be necessary.  Yes, it will produce a validation error, but a few validation errors _should_ be of little consequence if there are no detrimental impacts on the end user. 

There have been discussions on more explicitly stating what you suggest, and the worry there being that it gives browsers / AT a loophole to validate their bugs or undocumented/non-standard heuristics.  e.g., "we don't have to fix this, just use ARIA to fix it yourself"

**Comment by masi** [comment]
Lot's of warnings are an issue in the age of automated tests. I don't understand why a few wasted bytes are such an issue for you that you want to make a validation report looking more bad that it actually is.
