### ISSUE TITLE
role=tree on svg

### ISSUE THREAD

**Issue by pkra** [w3c/html-aria#261]
Could the spec allow SVGs to have role=tree? In my experience, browsers and ATs support this combination quite well.

**Comment by pkra** [comment]
Or, I suppose more generally, @LJWatson's point at https://github.com/w3c/html-aria/issues/158#issuecomment-513835335 to allow any role on svg (matching SVG-AAM).

**Comment by scottaohara** [comment]
Thanks for the issue @pkra.  yes, work on 158 may well resolve this issue.  Currently planning to discuss this with @stevefaulkner tomorrow or this week.

**Comment by pkra** [comment]
Thanks, @scottaohara.

**Comment by scottaohara** [comment]
takeaway on discussing this today: yes, we need to open up the allowed roles on svg elements, and I see no reason why `role=tree` would not be one of them.

I personally wonder if things like `role=textbox` and `role=searchbox` on the `<svg>` itself are necessary allowances...  noting that any roles are presently allowed on child elements of the `<svg>` so any possible need for those roles would be allowed within.  but I digress.  really just wanted to make it known that this will be updated.
