### ISSUE TITLE
header and footer elements

### ISSUE THREAD

**Issue by jongund** [w3c/html-aria#27]
It seems that the context to create banner and contentinfo landmarks using header and footer elements is quite large.
It seems the only context that header and footer don't create landmarks is when they are a descendant t of an article or section element role=banner.

This leaves header in main, section and many other sectioning elements creating banner and contentinfo landmarks.  I think the only time a header or footer element should create a banner or contentinfo landmark is when they are in the context of the body element.

**Comment by stevefaulkner** [comment]
> I think the only time a header or footer element should create a banner or contentinfo landmark is when they are in the context of the body element.

yes I agree with that, but this needs to be filed as an issue on the HTML-AAM spec as that is where the browser mappings are defined. have opened an issue https://github.com/w3c/aria/issues/277
