### ISSUE TITLE
clarifitations to hidden/aria-hidden

### ISSUE THREAD

**Issue by mtrootyy** [w3c/html-aria#270]
The following sentence should be added to the 3rd column of the row of "Any element with a hidden attribute".

> Authors MUST NOT use aria-hidden="false" on any element which also has a hidden attribute.

**Comment by scottaohara** [comment]
That's debatable as that is actually a use case which would make aria-hidden=false useful.

leaving this open but marking it as a question for future consideration / discussion with the aria wg

**Comment by scottaohara** [comment]
`aria-hidden=false` is now the same as `aria-hidden=undefined` or the complete absence of the attribute.  as such, no need to mention it.
