### ISSUE TITLE
References to "web developer"

### ISSUE THREAD

**Issue by LJWatson** [w3c/html-aria#271]
The references to "web developers" throughout seems to exclude DPub content authors, though the spec includes the DPub ARIA roles.

**Comment by scottaohara** [comment]
Yes.  seems to me this should just be changed to "authors"

**Comment by LJWatson** [comment]
That is the usual W3C parlance, yes.

**Comment by stevefaulkner** [comment]
This term was used deliberately as I know of no one that would consider themselves as "authors" except people who write books. Can i suggest we drop "web" and just use "developers"?

**Comment by scottaohara** [comment]
@LJWatson, @stevefaulkner I have removed instances of "web developer" and replaced with "developer" in [this commit](https://github.com/w3c/html-aria/commit/975bcd25714455a104d6e4e04e54fb8c00615d0f). 

The spec now uses both the terms "developer" and "author".  we can either leave this as is, or we can change them all to one or the other.

**Comment by marcoscaceres** [comment]
Developers is more "in vogue"... and thus, I'd urge us to follow Madonna.

**Comment by LJWatson** [comment]
> This term was used deliberately as I know of no one that would consider themselves as "authors" except people who write books.

Not everyone considers themselves a developer either.

The term "author" is used throughout W3C specifications as a simple way of referring to someone who authors a document, be it with words or code, so I do not recommend changing it.

**Comment by myfonj** [comment]
Unsolicited anecdotal evidence from stranger: ["Introduction" chapter of HTML spec](https://html.spec.whatwg.org/multipage/introduction.html) contains 62 occurrences of string `author` (inc. `authoring`), 4 occurrences of string `developer`.  There is even charming phrase _"novice author"_:

> [...] authors are encouraged to consult tutorials and guides. Some of the examples included in this specification might also be of use, but the novice author is cautioned that [...]

I understand that it might feel strange at first to refer to self as "author" while producing or enriching markup of content authored by different person, but I really doubt that people coming to ARIA specs will be exposed to this particular meaning for the first time and that they might get confused.
