### ISSUE TITLE
Wide review tracker

### ISSUE THREAD

**Issue by LJWatson** [w3c/html-aria#273]
It's been more than two years since we last went out for wide review (#79), meaning we need to do so again before requesting transition to CR.

Requests sent out today:
  
* [APA WG](https://lists.w3.org/Archives/Public/public-apa/2021Mar/0001.html)
* [ARIA WG](https://lists.w3.org/Archives/Public/public-aria/2021Mar/0000.html)
* W3C/i18n-request#150
* [Privacy](https://lists.w3.org/Archives/Public/public-privacy/2021JanMar/0024.html)
* W3CTAG/design-reviews#614
* [Security](https://lists.w3.org/Archives/Public/public-web-security/2021Mar/0000.html)
* [WebApps WG](https://lists.w3.org/Archives/Public/public-webapps/2021JanMar/0010.html)

An email has also been sent to the [public review announcement list](https://lists.w3.org/Archives/Public/public-review-announce/2021Mar/0000.html).

**Comment by LJWatson** [comment]
Reminders have been sent to:

* [APA WG](https://lists.w3.org/Archives/Public/public-apa/2021Apr/0020.html)
* [ARIA WG](https://lists.w3.org/Archives/Public/public-aria/2021Apr/0013.html)
* [PING](https://lists.w3.org/Archives/Public/public-privacy/2021AprJun/0002.html)
* [Web Security](https://lists.w3.org/Archives/Public/public-web-security/2021Apr/0002.html)

According to w3ctag/design-reviews#614, review is scheduled for this week.

Review by I18n is complete with no comments or issues, recorded on w3c/i18n-request#150.

**Comment by LJWatson** [comment]
Review status as of now:
* APA: No response
* ARIA WG raised #317, #318, and #319
* I18n had no issues, recorded in w3c/i18n-request#150
* PING raised #295 (resolved)
* TAG have not been able to provide feedback, noted in w3ctag/design-reviews#614
* Web Security were [not able to review](https://lists.w3.org/Archives/Public/public-web-security/2021Apr/0003.html)


@scottaohara  @stevefaulkner  and @patrickhlauke, once you've responded to the issues from the ARIA WG, and you've confirmed that the implementation report is complete (with any features without sufficient implementation experience removed or marked as "at risk" if you believe implimentations will be documented within a few weeks), we'll open the WG CFC to make the transition to CR.

**Comment by siusin** [comment]
The horizontal review is now closed.

**Comment by plehegar** [comment]
APA WG concluded [no need to re-review](https://www.w3.org/WAI/APA/wiki/ARIA_in_HTML).
