### ISSUE TITLE
Why include DPub Roles?

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/html-aria#279]
I'm a bit confused as to why the DPub Roles appear in this document? Their appearance in this document seem to duplicate what's already in the DPub Roles spec? Generally, we only want "one source of truth", so I'd suggest removing the DPub Roles unless there is some good reasons for having them in this document (e.g., this document makes the DPub Roles redundant).

**Comment by marcoscaceres** [comment]
Alternatively, this document should state why the DPub Roles are here in this document instead of referencing the other spec. If there is no good *technical* reason, then please remove them.

**Comment by stevefaulkner** [comment]
@marcoscaceres The dpub people asked us to include which dpub- roles can be used on which html elements same as we do for ARIA roles. We don't define the roles, only what roles can be used with a particular element.

**Comment by marcoscaceres** [comment]
Ah, got it. Thanks @stevefaulkner.
