### ISSUE TITLE
Links to "Any element where the * attribute is allowed"

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/html-aria#284]
The spec has, for example, "Any element where the max attribute is allowed". However, the "max" attribute is defined differently for different elements. The spec should really link to each attribute as appropriate.  

The same applies for the rest of the attributes.

**Comment by scottaohara** [comment]
noting updates regarding this were partially worked on in PR #285.  so any further work here should be done in that PR, or be aware of it so as to not make unnecessary conflicts

**Comment by scottaohara** [comment]
i think some of these definitely make sense to update.  where as some others, like the `hidden` attribute, make no sense to list out every (all) elements.  So I will update the instances here where I agree with you, and it makes sense to list them.  Otherwise, they'll remain "Any element..."

**Comment by marcoscaceres** [comment]
> like the hidden attribute, make no sense to list out every (all) elements. 

Agree. But `hidden` is a "global attribute" (I think... need to check), so the spec probably just needs rewording. 

In any case, not a big deal. Just want to make sure the terminology aligns with the HTML spec.

**Comment by scottaohara** [comment]
yes, it is global.

essentially my take on this is if the attribute link does not point to a single source in the HTML spec, then the elements / their references to that attribute can be linked.  e.g., your update to max as it related to meter, input and progress.

where as hidden is global, so linking to every element wouldn't be necessary.  and placeholder is only allowed on inputs / has a single definition - so can keep wording similar to what's there now, as listing out every input type that allows the placeholder is just unnecessary

**Comment by marcoscaceres** [comment]
> where as hidden is global, so linking to every element wouldn't be necessary.

Agree. That wouldn't make any sense. 

> and placeholder is only allowed on inputs / has a single definition - so can keep wording similar to what's there now, as listing out every input type that allows the placeholder is just unnecessary

Agree.
