### ISSUE TITLE
report todos

### ISSUE THREAD

**Issue by scottaohara** [w3c/html-aria#296]
Add tests and results for
- [x] img alt=sometext
- [x] img alt=""
- [x] img w/out alt
- [x] td within table / treegrid / grid (tests need publishing)
- [x] td within table[role=presentation]
- [x] tr within table / treegrid / grid (tests need publishing)
- [x] tr within table[role=presentation]
- [x] th within table / treegrid / grid (tests need publishing)
- [x] th within table[role=presentation]
- [x] Element that is a candidate for constraint validation but that does not satisfy its constraints 
- [x] tests for kinds of content / descendant restrictions (related to #54)

**Comment by scottaohara** [comment]
- [x] file issue with html validator for image results
- [x] file issue with html validator for tr, td, th (after tests published)
- [x] file issue with ibm for image results
- [x] file issue with ibm for tr, td, th (after tests published)

**Comment by stevefaulkner** [comment]
@scottaohara [img with some text does](https://w3c.github.io/html-aria/#el-img) not allow `role=radio`, deliberate omission? If not will add and reup test

**Comment by scottaohara** [comment]
Probably an oversight when we looked at tightening them up. Don’t think it makes much sense in practice but since we allow other similar roles, yeh. Add it @stevefaulkner

**Comment by LJWatson** [comment]
I'm chasing outstanding reviews in #273. If we have not heard from the relevant groups by the start of next week, I'll go ahead an open a CFC with WebApps to transition this to CR.

We typically allow one week for WG CFC, which will put us safely on the other side of the AC meeting publishing moratorium (23 to 29 April).

At that point we'll officially request transition, so the report should have at least two documented implementations for each feature, and the features where the implementation experience is TBC should be marked as "at risk" (so if we have not documented implementations by the time we want to move out of CR, we can do so without returning to WD first).

**Comment by scottaohara** [comment]
with PR #322, the todos are now complete
