### ISSUE TITLE
Editorial updates for 1.0

### ISSUE THREAD

**Issue by scottaohara** [w3c/html-aria#297]
- [x] add commits/substantial commits since last wide review section.
- [x] Remove instances of referring to this as a draft document.
- [x] question: add a note about dpub roles being conforming, but that they will likely not be understood in _web pages_ by browsers or AT.
- [x] any additional editorial clarifications that can be made which have not already been brought up in other issues.

**Comment by scottaohara** [comment]
i will handle the commits/substantial commits section

**Comment by stevefaulkner** [comment]
hid draft notice https://github.com/w3c/html-aria/commit/043b124baefe0e1086347bdff62be05ae30b6382

**Comment by patrickhlauke** [comment]
proposed a few changes/tweaks https://github.com/w3c/html-aria/pull/306

**Comment by scottaohara** [comment]
closing as any additional editorial updates beyond what already have PRs should be small / can wait till the next release.
