### ISSUE TITLE
`<ul>`/`<li>` as `radiogroup`/`radio`?

### ISSUE THREAD

**Issue by alice** [w3c/html-aria#30]
https://www.w3.org/TR/html-aria/#docconformance does not list `radiogroup` as an option for `<ul>`, nor `radio` as an option for `<li>`. Is this an oversight, or deliberate? If the latter, what is the reasoning?

**Comment by mcking65** [comment]
This must be an oversight. It does not make any sense since UL may be cast a tree, menubar, etc.

**Comment by stevefaulkner** [comment]
@alice firstly apologies for not responding earlier, secondly the reasoning: in general the conformance rules are designed to dissuade developers from overriding native semantics. In the case of `UL`, since `radio` is not allowed for `li` it does not make sense to allow `radiogroup` to override `ul`. If you can provide examples of this pattern `ul/radiogroup, li/radio` used in wild it would be helpful, PS: WAI examples do not count ;-)

**Comment by jnurthen** [comment]
It seems strange to me that Ul/LI allows listbox/option but not radiogroup/radio as these are logically the same thing.

**Comment by alice** [comment]
Right, as @jnurthen alluded to: why does the reasoning about "dissuading developers from overriding native semantics" not apply equally to using "menuitem, menuitemcheckbox, menuitemradio, option, presentation, separator, tab, or treeitem" on `li`?

**Comment by alice** [comment]
As to why you'd want to use `radio`/`radiogroup` on `li`/`ul` respectively, the default presentation of a `ul` is very similar to a `radiogroup`, plus they are structurally very similar (a grouping element containing a list of options), so it's very little work to adjust the presentation and script to make it work as a `radiogroup`. 

http://udacity.github.io/ud891/lesson2-focus/05-radio-group/ has a nice example (in fact the motivating example for this question).

**Comment by stevefaulkner** [comment]
@alice, ok thanks, will look into it and get back to you.

**Comment by stevefaulkner** [comment]
I will try to make sense of the taxonomy diagram https://www.w3.org/TR/wai-aria/rdf_model.svg which may be helpful...

**Comment by stevefaulkner** [comment]
@alice have reviewed taxonomy and agree that this should be allowed
