### ISSUE TITLE
Should <iframe> support role=dialog?

### ISSUE THREAD

**Issue by cyns** [w3c/html-aria#318]
<iframe>s and dialogs have a lot in common, and it seems like it would be useful to change the role of an <iframe> to dialog or alertdialog in some situations. Can this be supported? Is not supporting it due to implementation limitations or intentional design?

**Comment by stevefaulkner** [comment]
I am not opposed to this, at the time it was decided it was based on the the flaky way `iframe` was exposed in the acc tree across browsers. If it is shown that `role=dialog` is interoperably supported in a practical way then OK.

**Comment by scottaohara** [comment]
Closing this issue to piggy back off from an existing issue about adjusting `iframe`'s allowed roles.

This will be tested / considered for the next version of the spec.
