### ISSUE TITLE
Should role option be allowed on A element with HREF

### ISSUE THREAD

**Issue by mcking65** [w3c/html-aria#32]
In table: "Rules of Accessible Rich Internet Applications  attributes usage by HTML language feature"

For row: "a element with a href"
The allowed roles are: button, checkbox, menuitem, menuitemcheckbox, menuitemradio, radio, tab, switch, or treeitem

Is role option intentionally left out? If so, why?

**Comment by stevefaulkner** [comment]
thanks @mcking65, unintentional fixed by https://github.com/w3c/html-aria/commit/cb4ed97c45b93352425a1260fa5524214db53fbe
