### ISSUE TITLE
CFC: transition Aria in HTML to CR

### ISSUE THREAD

**Issue by LJWatson** [w3c/html-aria#326]
This is a Call For Consensus (CFC) to transition [ARIA in HTML](https://www.w3.org/TR/html-aria/) to Candidate Recommendation (CR).

The results of the most recent horizontal review were tracked in #273, and there are no outstanding issues.

An [implementation report](https://w3c.github.io/html-aria/results/implementation-results.html) is also available. All but 14 features have at least two implementations, and those 14 are noted as being "at risk" should the implementations not happen before we exit CR.  

If you support this proposal, please add a "thumbs up" reaction to this comment.

If you do not support the proposal, please add a "thumbs down" reaction to this comment instead, and post a comment with your reasons.

If you do not respond to this CFC at all, W3C convention regards it as implicit support for the proposal. It is therefore much better if you respond directly.

Please respond to this CFC by the end of your day on Friday 25 July 2021. Thank you.

**Comment by LJWatson** [comment]
Ping @scottaohara, @stevefaulkner, @patrickhlauke, and @marcoscaceres.

**Comment by scottaohara** [comment]
note: additional HTML Validator updates have reduced the at risk features list [by two items](https://github.com/w3c/html-aria/commit/557c90efc8b0e996fc05f68e2e67d2918199f634#diff-ccba1135581d570f1c32c939b9c9fe11b8163456e5acde9f589eb106d3161525)

**Comment by marcoscaceres** [comment]
Given that now all engines handle case insensitive matching, I'd still like to see issue #280 addressed and #287 merged.

**Comment by scottaohara** [comment]
I have commented on #287

**Comment by scottaohara** [comment]
As of today, the number of features at risk is now 9

**Comment by scottaohara** [comment]
As of today, the number of features at risk is now 1

**Comment by LJWatson** [comment]
With thanks to everyone who responded, this CFC passes with multiple expressions of support and no objections.

**Comment by scottaohara** [comment]
Update: number of features at risk is now zero.
