### ISSUE TITLE
Respec errors: references for `audio` and `menu` broken

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/html-aria#328]
This feels like a respec error ... no proper way to reference `audio` nor `menu` seem to be available

https://respec.org/xref/?term=audio&specs=html

https://respec.org/xref/?term=menu&specs=html

https://w3c.github.io/html-aria/

/cc @marcoscaceres

**Comment by patrickhlauke** [comment]
another change to respec that broke stuff...?

**Comment by scottaohara** [comment]
for now, i replaced `[^audio^]` and `[^menu^]` with the `<a data-cite="html/...">...</a>` versions to work around these errors / get the links to work again.  realizing that this is not what we actually want to have here, but I also don't want broken references in the spec while we wait for external fixes.

**Comment by marcoscaceres** [comment]
I spotted those too. Need to check why they went missing from the references database (https://github.com/w3c/webref). Note that ReSpec just links them, so this is not a Respec bug.

**Comment by marcoscaceres** [comment]
Issue was in HTML spec: https://github.com/whatwg/html/pull/6790 

Remember, if something is missing, it's usually at the source.

**Comment by patrickhlauke** [comment]
> Remember, if something is missing, it's usually at the source.

This makes the publication process quite brittle though (as any commit is not published publicly if it fails respec validation). Any referenced spec messes up, and *you* are prevented from publishing. Can this be changed (so it's still possible for us to publish even though it has a respec error that's not our fault)? Yes, you'd then see the respec error in https://w3c.github.io/html-aria/ ... but at least it'd still publish there.

**Comment by marcoscaceres** [comment]
> This makes the publication process quite brittle though (as any commit is not published publicly if it fails respec validation).

We are working on that. We want to do a check whereby if you have exported a term, a spec validator will yell at you if you delete it (and let you know which specs are breaking).  

> Any referenced spec messes up, and you are prevented from publishing. 

That's good tho. It makes the community work together. 

>Can this be changed (so it's still possible for us to publish even though it has a respec error that's not our fault)? Yes, you'd then see the respec error in https://w3c.github.io/html-aria/ ... but at least it'd still publish there.

It can, but that would be bad form. If someone breaks us, we go and collaborate with them to fix it (like whatwg/html#6790). 

It's not a big deal. Love thy neighbor, Patrick H! Don't be a spec-references-ecosystem-citations-cross-reference-hater.

**Comment by patrickhlauke** [comment]
The process works fine for other specs (e.g. Pointer Events can be published to github.io even with respec errors). I find it silly to prevent publication of an editor's draft *here* because some other spec messed up.

**Comment by marcoscaceres** [comment]
It's not published *here*, it's on the Internationally renowned /TR/ space.

**Comment by marcoscaceres** [comment]
to be clear, when you merge a pull request, it immediately goes on TR.

**Comment by patrickhlauke** [comment]
> It's not published _here_, it's on the Internationally renowned /TR/ space.

nope, if respec fails, it also stops publishing https://w3c.github.io/html-aria/

by all means, stop the copying over to /TR/, but let the github.io one be published

**Comment by marcoscaceres** [comment]
It's not "failing" tho. The errors are telling you there is something that needs to be fixed.

**Comment by marcoscaceres** [comment]
I don't know why fixing things is such a bother? Look at whatwg/html#6790 (which literally took 2 minutes to send a fix for). If it wasn't for this error, we wouldn't of discovered the issue in the HTML spec. 

That's a net positive for the community as a whole. 

Having said that, if you *urgently* need to merge something, you can just use admin right to force a merge:
 
![Screen Shot 2021-06-23 at 12 11 35 am](https://user-images.githubusercontent.com/870154/122940162-9360c280-d3b7-11eb-9e3d-2c92ab4eaf34.png)

It's why all the editors have admin rights.

**Comment by patrickhlauke** [comment]
you can merge it, but it won't be viewable anywhere (not even on github.io) though until other people fix their errors in their spec. can you not see how that's a bit...odd? anyway...

**Comment by marcoscaceres** [comment]
> you can merge it, but it won't be viewable anywhere (not even on github.io) though until other people fix their errors in their spec.

I don't follow? If you merge, should be there on github.io... you will just get a red squiggle under a thing that didn't link? 

> can you not see how that's a bit...odd? anyway...

It is. If you merge, you merge? Why would it not show up on gh-pages? Are you sure?

**Comment by marcoscaceres** [comment]
Just to be sure we are talking about the same thing: https//w3c.github.io/html-aria/ is what's on gh-pages. It's just the raw Respec doc (same as you would see locally). So anything you force merge onto that branch will show up there.

**Comment by patrickhlauke** [comment]
> > you can merge it, but it won't be viewable anywhere (not even on github.io) though until other people fix their errors in their spec.
> 
> I don't follow? If you merge, should be there on github.io... you will just get a red squiggle under a thing that didn't link?
> 
> > can you not see how that's a bit...odd? anyway...
> 
> It is. If you merge, you merge? Why would it not show up on gh-pages? Are you sure?

unless it was some weird unrelated timing issue, that's what happened to me the other day ... made this commit to at least fix one of the respec issues we saw, and to change the reference of something else ... https://github.com/w3c/html-aria/commit/a63ca191c61e51970e33ac2d2bb41dc17d2161eb ... but https://w3c.github.io/html-aria/ wasn't updating. it only updated once @scottaohara also temporarily patched the other errors here https://github.com/w3c/html-aria/commit/eb75d5738543df5854829cb8a01bb574d455da37

**Comment by marcoscaceres** [comment]
Oh, right... yes, it can take around 20 seconds to 1 minute for things to show up on gh-pages after merge. Sometimes, if Github is having issues (like it happens every few weeks), it can take a little longer.

**Comment by marcoscaceres** [comment]
@patrickhlauke, someone pointed me to:
https://github.com/w3c/html-aria/deployments/activity_log?environment=github-pages

It allows you to see if a gh-pages deployment succeeded. Could be useful the case you described above where for whatever reason gh-pages doesn't get updated.
