### ISSUE TITLE
Status report and planning for TPAC 2021

### ISSUE THREAD

**Issue by LJWatson** [w3c/html-aria#343]
[TPAC](https://www.w3.org/2021/10/TPAC/#schedule) will be virtual again this year. There will be a WebApps WG meeting at some point between 24 and 29 October.

There are two things we need you to do in the meantime:
1. Let @marcoscaceres  and I know before 17 September if you plan to hold a specification specific meeting (in addition to the general WebApps WG meeting)
2. Post a specification status report before 30 September

Your specification status report should include:
* What progress has your spec made in the last 12 months?
* Is anything blocking your spec from moving to CR?
* If yes, what is your plan to unblock it and do you need any help?

CC @siusin

**Comment by scottaohara** [comment]
Status report:
* **What progress has your spec made in the last 12 months?**: Spec went to CR / going into PR. Preparing tasks for next version of spec.
* **Is anything blocking your spec from moving to CR?**: No
*  **If yes, what is your plan to unblock it and do you need any help?**: Not blocked.

Further updates: while we wait through the process for ARIA in HTML to reach official rec status, we have begun planning the next batch of updates for the specification.  The issues/PRs that are presently in consideration for the next version of the spec are being tracked [in this milestone](https://github.com/w3c/html-aria/milestone/2).  Tasks may be added / removed from this milestone as we determine priorities.

cc @LJWatson, @stevefaulkner, @patrickhlauke
