### ISSUE TITLE
Proposal: role="subheading"

### ISSUE THREAD

**Issue by carnoxen** [w3c/html-aria#347]
## What is this?
The subtitle for its parent heading element.

## Example
```html
<h1>title <span role="subheading">and subtitle</span></h1>
```

## Reason for proposal
It might alternate ```<hgroup>``` element.

I know that ```role="doc-subtitle"``` already exists. But "subheading" is more consistent with heading role element.

**Comment by scottaohara** [comment]
@carnoxen you have [already requested this role from the ARIA working group](https://github.com/w3c/aria/issues/1378) (which is the proper place to have filed this issue).  

This is not the place to request new roles, as the purpose of this spec is to define how ARIA may be used in HTML - where as the ARIA spec actually defines the roles and attributes of ARIA. And it's not helpful to duplicate issues.  So I'm going to close this one.

**Comment by carnoxen** [comment]
Then please erase this issue

**Comment by carnoxen** [comment]
How can i delete this issue? I want to do.

**Comment by carnoxen** [comment]
> @carnoxen you have [already requested this role from the ARIA working group](https://github.com/w3c/aria/issues/1378) (which is the proper place to have filed this issue).  
> 
> 
> 
> This is not the place to request new roles, as the purpose of this spec is to define how ARIA may be used in HTML - where as the ARIA spec actually defines the roles and attributes of ARIA. And it's not helpful to duplicate issues.  So I'm going to close this one.

Hey if you have a permission please erase this issue

**Comment by scottaohara** [comment]
it's closed.  i'd rather not delete issues unless they're flagrant spam.

**Comment by carnoxen** [comment]
> it's closed.  i'd rather not delete issues unless they're flagrant spam.  

Okay.
