### ISSUE TITLE
Consistent hyperlinks to HTML 5.1

### ISSUE THREAD

**Issue by paulbrucecotton** [w3c/html-aria#36]
This specification normatively references HTML 5.1:

[HTML51]

Steve Faulkner; Arron Eicholz; Travis Leithead; Alex Danilo. W3C. HTML 5.1. 3 May 2016. W3C Working Draft. URL: http://www.w3.org/TR/html51/ 

Most of the hyperlinks in this document especially those in [Section 3](http://www.w3.org/TR/2016/WD-html-aria-20160525/#docconformance) are directly into the HTML 5.1 specification.  For example, "[a](http://www.w3.org/TR/html51/semantics.html#the-a-element) element with a [href](http://www.w3.org/TR/html51/semantics.html#attr-hyperlink-href)" uses references of the http://www.w3.org/TR/html51/semantics.html#the-a-element which link are DIRECTLY to the HTML 5.1 specification.

But there are several occurrences in the document a references to "[HTML elements](http://www.w3.org/TR/html/dom.html#elements)"  which use references of the form http://www.w3.org/TR/html/dom.html#elements.  These only point to HTML 5.1 since http://www.w3.org/TR/html currently re-directs to HTML 5.1.  

Should all the references in this specification point DIRECTLY to HTML 5.1?

**Comment by stevefaulkner** [comment]
fixed by https://github.com/w3c/html-aria/commit/9a1cdf6f7d5aa40f34ea242273d1528f84053f05 and https://github.com/w3c/html-aria/commit/db091995f2cd538c3e28844a3162fbc2ee5dbacd and https://github.com/w3c/html-aria/commit/94d0bcb3f8928812cfc7d707f7b15551986f7116
