### ISSUE TITLE
Aria-checked and the checked state of a checkbox

### ISSUE THREAD

**Issue by FremyCompany** [w3c/html-aria#37]
@stevefaulkner mentioned on twitter that he believes `<input type=checkbox checked aria-checked=false />` should output a `checkbox[checked=true]` in the accessibility tree.
### The argument is rooted in the following three pieces of text from wai-aria:

> Except for the cases outlined below, user agents MUST always use the WAI-ARIA semantics to define how it exposes the element to accessibility APIs, rather than using the host language semantics.

and

> Host languages MAY document features that cannot be overridden with WAI-ARIA (these are called "strong native semantics"). 

or

> When a host language declares a WAI-ARIA attribute to be in direct semantic conflict with a native attribute for a given element, user agents MUST ignore the WAI-ARIA attribute and instead use the host language attribute with the same implicit semantic.
### As far as I can tell, none of two exceptions apply in this case, however.

As we can see in the following table from [HTML-ARIA](http://www.w3.org/TR/html-aria/), aria-checked is allowed on a checkbox (second column lists implied things, the third list the other allowed things):

> <a href="http://www.w3.org/TR/html-aria/#docconformance" title="input type= checkbox: allow global aria-* attributes and any aria-* attributes applicable to the allowed roles">![image](https://cloud.githubusercontent.com/assets/364405/17494827/42cd14e4-5d6b-11e6-86c9-f2845c587182.png)</a>
> <a href="http://www.w3.org/TR/html-aria/#index-aria-checkbox" title="checkbox: A checkable input that has three possible values: true, false, or mixed. Allows aria-checked (state)">![image](https://cloud.githubusercontent.com/assets/364405/17495248/3f3a6334-5d6d-11e6-8cc5-6ffaf2301e94.png)</a>

And there is no host attribute that share the same semantic as aria-checked. The "checked" attribute means "defaultChecked" which is the value of the checkbox is the user never interacted with it. Click on the textbox once (or set its value via javascript) and the checked attribute can now be added, removed, changed without any impact on the checkbox. As a result, it is not a candidate for the "prefer html attribute over aria if they are identical" exception.
### So, we are left with `aria-checked > intrinsic semantics`, which is what Edge is doing.

Please note that this does not apply to other attributes like "readonly" which does have an aria exception stated in the spec. There is also an exception for "required" but I think the spec is unintentionally misleading in this case.
<a href="http://www.w3.org/TR/html-aria/#docconformance" title="prose for required and readonly attribute, do not match in recommendations">![image](https://cloud.githubusercontent.com/assets/364405/17495546/4ea6d90a-5d6e-11e6-9675-a00a23a8ee34.png)</a>

What do you think?
@cyns?

**Comment by stevefaulkner** [comment]
Note: ARIA in HTML does not define the implicit semantics for HTML elements, nor does the ARIA spec, these are defined in the HTML Accessibility API spec. The [implementation definition for checkbox](https://w3c.github.io/html-aam/#el-input-checkbox) is defined in the HTML API spec. If there are differences in observed implementation behaviour, please [open an issue](https://github.com/w3c/html-aam/issues/) on that spec.
