### ISSUE TITLE
Allowances for proposed search element

### ISSUE THREAD

**Issue by scottaohara** [w3c/html-aria#371]
Under the assumption that HTML will eventually merge the proposed `search` element into the spec, we would need to also provide role and aria-* attribute allowances.

I have some initial thoughts, but am creating this issue as a TODO and to let other people weigh in, if they so choose.

**Comment by domenic** [comment]
It would be great if we had a PR ready for this on html-aria (and html-aaam) before we landed https://github.com/whatwg/html/pull/7320. Let me know if I can help!

**Comment by scottaohara** [comment]
@domenic PR is made.  I can merge this whenever the time is right.
