### ISSUE TITLE
datalist doesn't actually resepct/expose aria-* attributes

### ISSUE THREAD

**Issue by scottaohara** [w3c/html-aria#382]
Presently the `datalist` allows for global aria-* attributes and any aria-* attributes applicable to the listbox role. 

In reality no aria-* attributes are respected on the `datalist` since its rendered ui is completely controlled by the browser. 

The `datalist` attribute allowances should be updated to reflect this reality and simply indicate no ARIA attributes are allowed on this element.

**Comment by carmacleod** [comment]
Will it still have the implicit role of `listbox`?

**Comment by scottaohara** [comment]
yes.  that's the implicit role for the `datalist`.
