### ISSUE TITLE
Behaviour unclear if conflicting img roles/attributes specified

### ISSUE THREAD

**Issue by dd8** [w3c/html-aria#41]
It's not clear from the spec what happens if any of the following are specified

&lt;img alt=“A vital image” role=“presentation” src=“1.png” /&gt;
&lt;img alt=“” arial-label=“A vital image” src=“1.png” /&gt;
&lt;img aria-label=“A vital image” role=“presentation” src=“1.png” /&gt;
&lt;img alt=“” title=“A vital image” src=“1.png” /&gt;

Author intent is unclear in this markup since it's both presentational and has an accessible name. About 50% of AT combos treat it this as presentational and ignore it, the other 50% read the accessible name.

**Comment by stevefaulkner** [comment]
`<img alt=“A vital image” role=“presentation” src=“1.png”>`

an img with a non-empty `alt` cannot have `role=presentation` or `role=none`
http://w3c.github.io/html-aria/#img
@sideshowbarker this currently does not throw an error, it should

`<img alt=“” arial-label=“A vital image” src=“1.png”>`
- an img with a empty `alt` cannot have any  aria-* attributes except `aria-hidden`
- can only have `role=presentation` or `role=none`
it throws an error: 
> Attribute `aria-label` not allowed on element `img` at this point.

`<img aria-label=“A vital image” role=“presentation” src=“1.png”>`
is non conforming, it throws an error: 
> An `img` element must have an `alt` attribute, except under certain conditions.

The following case is not defined in this spec as it does not involve the use of ARIA attributes

`<img alt=“” title=“A vital image” src=“1.png” />`

**Comment by stevefaulkner** [comment]
I have updated the spec to make it clearer, if you still think it needs work, please re-open.
