### ISSUE TITLE
Missing link fragments

### ISSUE THREAD

**Issue by momdo** [w3c/html-aria#42]
In the section Web developer requirements for use of ARIA in HTML,

http://www.w3.org/TR/html/infrastructure.html#strong-native-semantics
http://www.w3.org/TR/html/infrastructure.html#default-implicit-aria-semantics

these id fragments are missing.

**Comment by stevefaulkner** [comment]
thanks! @momdo fixed by https://github.com/w3c/html-aria/commit/bddc7d62fd734b073e3e8312ee1dd2e440681ee6

now point directly to aria 1.1
