### ISSUE TITLE
input[type=password] why is default role not textbox

### ISSUE THREAD

**Issue by jongund** [w3c/html-aria#422]
Curious why the default role for input[type=password] is "no corresponding  role" and not textbox?

**Comment by scottaohara** [comment]
there is this: https://github.com/w3c/aria/issues/935

it's not _just_ a textbox, as there are other specific mappings to it.  it wouldn't be accurate to say it cleanly maps to role=textbox. 

So going to close this as this spec is accurate since there is no corresponding aria role.
