### ISSUE TITLE
404 broken links on Aria in HTML site - section 4, global properties

### ISSUE THREAD

**Issue by mark-rossiter** [w3c/html-aria#43]
# Observed

On the Aria in HTML web page under section 4 > the Supported Properties column > no hyperlinks in this column redirect to a useful page, instead 404 page is displayed. 
# Expected

Links should send you to a page that provides more detail for that role.
# Steps

1) Go to http://w3c.github.io/html-aria/#index-aria-global
2) Scroll down to section 4. "Allowed ARIA roles, states and properties"
3) Click any link under the Supported Properties column

**Comment by stevefaulkner** [comment]
@mark-rossiter thanks, have fixed should be good now
