### ISSUE TITLE
missing table or redundant section?

### ISSUE THREAD

**Issue by chaals** [w3c/html-aria#45]
Section 2 talks about the following table. Then there is a note. Then section 3, which talks about the following table. It looks to me like the two sections are really one, talking about the same table, but in any event it is extremely confusing.

**Comment by stevefaulkner** [comment]
thanks @chaals, fixed as part of https://github.com/w3c/html-aria/commit/9a1cdf6f7d5aa40f34ea242273d1528f84053f05 let me know if its still unclear

**Comment by chaals** [comment]
Hi @stevefaulkner, yeah, it's still unclear.

Section 2 talks about "the following table". There is no table. Then there is a new section, section 3, and that talks about "the following table" and there is a table following.

If both things refer to the same table - which is my assumption - you could make them a single section. If there is a table **missing**, I don't know what it looks like...

I can make a PR if you like.

**Comment by stevefaulkner** [comment]
yeah i noticed that it was still unclear, i thought I had edited it but apparently not, have tried again, please review https://w3c.github.io/html-aria/#docconformance

**Comment by chaals** [comment]
LGTM now. Thanks
