### ISSUE TITLE
"anchor with href": switch attribute not in alphabetical order

### ISSUE THREAD

**Issue by carmacleod** [w3c/html-aria#46]
https://w3c.github.io/html-aria/#docconformance

In the "a element with a href" row, the 3rd column lists the following:
Roles: button, checkbox, menuitem, menuitemcheckbox, menuitemradio, radio, tab, switch - (new)or treeitem

Switch should come after radio and before tab.  :)

**Comment by ZoeBijl** [comment]
Fixed in https://github.com/w3c/html-aria/commit/b323445956ca8019fafbdd3472b4e6dd260f8682
