### ISSUE TITLE
Remove param element

### ISSUE THREAD

**Issue by scottaohara** [w3c/html-aria#460]
it is marked as obsolete / non-conforming in HTML

**Comment by SamantaTarun** [comment]
I'd like to work on it. Please clarify it once.

**Comment by AVUKU-PRAGATHESWARI** [comment]
May I know the issue in detail so that i can work on it .

**Comment by scottaohara** [comment]
per https://github.com/w3c/html-aam/issues/486, rethinking this.  should probably just note it as obsolete - maybe even do similar to what'll be done in HTML AAM and create an obsolete section/table as well.
