### ISSUE TITLE
Potential conflict with WAI-ARIA on <link> element role

### ISSUE THREAD

**Issue by jlp-craigmorten** [w3c/html-aria#467]
In https://w3c.github.io/html-aria/#docconformance the `<link>` element is listed as having "no corresponding role".

This potentially conflicts with WAI-ARIA 1.2 which lists the `<link>` element as a "related concept" for the `link` role. See https://www.w3.org/TR/wai-aria-1.2/. I believe it is typical to only list elements as related concepts if they have that role as their implict role (perhaps under certain conditions).

Should the role mapping be updated in this specification to mirror the implication made by WAI-ARIA, or should WAI-ARIA be updated to remove the `<link>` element reference from the related concepts? Equally, have I misunderstood the meaning of "related concepts" in this instance and the specs are fine as-is?

If a change is needed to this spec then we should also look to raise an issue against HTML-AAM as it too lists the role as "no corresponding role", see https://w3c.github.io/html-aam/#html-element-role-mappings.

**Comment by pkra** [comment]
>  Equally, have I misunderstood the meaning of "related concepts" in this instance and the specs are fine as-is?

I think so.

To quote https://w3c.github.io/aria/#relatedConcept

> 5.1.3 Related Concepts
> Informative data about a similar or related idea from other specifications. Concepts that are related are not necessarily identical. Related concepts do not inherit properties from each other. Hence if the definition of one concept changes, the properties, behavior, and definition of its related concept is not affected.

It continues with an example. 

Looking at other examples also shows how lose this relationship can be. For example, the button role lists the link role as a related concept.
