### ISSUE TITLE
Test and mention some user-agents that have an implicit role for <summary>

### ISSUE THREAD

**Issue by Brian-Pob** [w3c/html-aria#484]
This issue in the MDN Web Docs https://github.com/mdn/content/issues/28446 mentions that Chrome browsers use `generic` as the implicit role while Firefox uses `summary` as the implicit role.

It might be worth mentioning in the NOTE for the [summary](https://html.spec.whatwg.org/multipage/interactive-elements.html#the-summary-element) element the behavior of a few of the most popular browsers.

<img width="865" alt="CleanShot 2023-08-16 at 04 03 06" src="https://github.com/w3c/html-aria/assets/29676413/21e47dbf-c145-4e7e-a247-0014b3f76e4a">

<img width="698" alt="CleanShot 2023-08-16 at 04 01 06" src="https://github.com/w3c/html-aria/assets/29676413/2ca5ae07-bbf7-4c26-864c-0a0a11325a3a">

P.S.
My apologies if user-agent/browser-specific details are not allowed in the official specs. I am new to this.

Thank you

**Comment by scottaohara** [comment]
hi @Brian-Pob 

thanks for the heads up, i'm going to respond in more detail over on the MDN issue.  But yeh, this sort of information doesn't belong here.  This spec doesnt even actually normatively define the role for HTML elements.  That happens in the HTML AAM spec (linked to for each element in this spec) - and there too that's for how the browser engines are supposed to map the element.  that spec would not get into the individual browser support, as that's not the point of the spec.

**Comment by Brian-Pob** [comment]
Understood. Thanks for the extra information!
