### ISSUE TITLE
separator role on button

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/html-aria#488]
Gerard Cohen asked me why `role=separator` is not allowed on a `button` element. From reading the [definition](https://www.w3.org/TR/wai-aria-1.2/#separator) in the aria spec, i don't see a reason not to allow.

you wizened souls may think otherwise?

**Comment by scottaohara** [comment]
naw, that seems quite reasonable esp. since it can represent an interactive control that a button could reasonably serve as a base for.

**Comment by scottaohara** [comment]
and boosh.  easy PRs are easy.  gotta inform the checkers now / get some implementation commitments to acknowledge this change, and then it can be merged if good to go

**Comment by gerardkcohen** [comment]
Thanks @stevefaulkner and @scottaohara
