### ISSUE TITLE
Text change

### ISSUE THREAD

**Issue by ZoeBijl** [w3c/html-aria#49]
“global aria-* attributes and any aria-* attributes applicable to the allowed roles and the link role” or a similar line is seen a few times in the “Rules of ARIA attributes usage by HTML language feature” table.

Would it make sense to change that to something like:

“global aria-* attributes and any aria-* attributes applicable to the implicit or allowed roles”

It has the benefit of being a bit shorter and you don’t have to change it for every different role.

+@handcoding

**Comment by stevefaulkner** [comment]
> attributes **applicable to the implici**t or allowed roles

is not always the case.

**Comment by ZoeBijl** [comment]
Ah, okay. Can close this than.
