### ISSUE TITLE
Wrong implicit role for hgroup element

### ISSUE THREAD

**Issue by kantoche** [w3c/html-aria#496]
Hi,

Since 21 August 2023 - Addition (see below), implicit role of hgroup element must be "group", but the "generic" value is still associated to this element (see https://www.w3.org/TR/html-aria/#el-hgroup)

> [21 August 2023 - Addition:](https://github.com/w3c/html-aria/pull/462) Update the [address](https://www.w3.org/TR/html-aria/#el-address) and [hgroup](https://www.w3.org/TR/html-aria/#el-hgroup) element allowances per their updated mapping to the group role.

**Comment by scottaohara** [comment]
Thank you for noticing the error
