### ISSUE TITLE
likely a typo: "parent list item" should be "parent list element"

### ISSUE THREAD

**Issue by Zhang-Junzhi** [w3c/html-aria#512]
The [spec](https://www.w3.org/TR/html-aria/#docconformance) says about ARIA role, state and property allowances for `<li>`:

> [No role](https://www.w3.org/TR/html-aria/#dfn-no-role) other than [listitem](https://www.w3.org/TR/html-aria/#index-aria-listitem), which is NOT RECOMMENDED, if the parent list element has an implicit or explicit list role.
> 
> Otherwise, [any role](https://www.w3.org/TR/html-aria/#dfn-any-role) if the **parent list item** does not expose an implicit or explicit list role.

The text in bold might be a typo. I think it means **parent list element**.

**Comment by scottaohara** [comment]
thanks for catching this
