### ISSUE TITLE
Should meter element allow all aria-* attributes allowed on meter role?

### ISSUE THREAD

**Issue by straker** [w3c/html-aria#517]
Currently the [meter element](https://www.w3.org/TR/html-aria/#el-meter) is listed as only allowing global aria-* attributes, but does not allow any of the aria-* attributes allowed on the `meter` role (though does make note to not use `aria-valuemax` or `aria-valuemin`). Is this indeed correct or does the meter element allow using allowed aria-* attributes of the `meter` role, such as `aria-valuetext`?

Other elements that are restricted to a single allowed role (but also not recommend to use that role), such as [input[type=url]](https://www.w3.org/TR/html-aria/#el-input-url), are documented as allowing aira-* attributes allowed on the implicit role with the text "any aria-* attributes applicable to the allowed role."

**Comment by scottaohara** [comment]
thanks @straker.  this is a miss and should be similar to the progress role.  i'll make a quick PR to fix this
