### ISSUE TITLE
Respec table styling changed causing overlap issues

### ISSUE THREAD

**Issue by scottaohara** [w3c/html-aria#518]
seems something changed with the styles for tables, so now the sticky column headers have no background when scrolling the page. the header column text now overlays the table text w/no background so the header text is difficult to read.

need to add a custom style to fix this, since the sticky headers are custom to this spec

**Comment by marcoscaceres** [comment]
Yeah, we are deferring more styles to the W3C... if you can avoid adding a custom style, that would be better (because of things like dark mode, etc... or anything else that could change in the future). Instead, file a bug on http://github.com/w3c/tr-design

**Comment by scottaohara** [comment]
closed by PR #520 removing the sticky header css
