### ISSUE TITLE
span element's role mapping should be "No Role"

### ISSUE THREAD

**Issue by dylanb** [w3c/html-aria#52]
Currently it specifies it as "no corresponding role", but this is inaccurate

https://www.w3.org/TR/html-aria/#span

**Comment by stevefaulkner** [comment]
> Currently it specifies it as "no corresponding role", but this is inaccurate

how so?

refer to https://w3c.github.io/html-aam/#el-span

**Comment by dylanb** [comment]
a role of "presentation" or "none" would be more accurate AND it differs from the designation for `<div>` which makes no sense

**Comment by stevefaulkner** [comment]
> a role of "presentation" or "none" would be more accurate AND it differs from the designation for <div> which makes no sense

The implicit ARIA role for all elements are not defined in this spec, it is defined in the HTML acc API spec, which defines it as "no corresponding role".  `div` is incorrect, it should also be "no corresponding role" as per the HTML acc API spec, thanks for pointing out the discrepancy.

**Comment by stevefaulkner** [comment]
updated `div`. Note in the context of the spec 'No role' and 'No corresponding role' [mean the same thing](https://www.w3.org/TR/html-aria/#dfn-no-corresponding-role). The term 'no role' was replaced with 'no corresponding role' to align the terminology with the html acc API spec.
