### ISSUE TITLE
Difficult to read correction under "Document conformance requirements..."

### ISSUE THREAD

**Issue by rschristian** [w3c/html-aria#529]
Not quite sure what the preferred styling is here, but as it sits, this correction is quite difficult to read as it overlaps text quite considerably:

![Image showing the problematic display of the text. The inline correction styling has a height greater than the text height, resulting in it overlapping the lines above & below, obstructing them](https://github.com/user-attachments/assets/ebcc4045-2b3c-4eea-ab2d-d145f8d6d1f6)

https://www.w3.org/TR/html-aria/#docconformance

**Comment by scottaohara** [comment]
looks like respec changed their styles a bit.  the style is meant to indicate an update since the last published version.  

i'll make a modification in our own style sheet to fix this up a bit.

**Comment by rschristian** [comment]
Thanks! I figured as much re: update, just wasn't sure if it was supposed to be inline, a separate block, etc.

**Comment by pkra** [comment]
Following #531, https://w3c.github.io/html-aria/#docconformance seems fixed.
