### ISSUE TITLE
Clarify difference on what applicable roles can be applied to the menu element

### ISSUE THREAD

**Issue by cpandhi** [w3c/html-aria#53]
As per the [document conformance table](https://www.w3.org/TR/html-aria/#docconformance), it states:
menu type = context 	role=menu 	global aria-* attributes and any aria-* attributes applicable to the toolbar role
The html 5.1 spec states: [https://www.w3.org/TR/html/interactive-elements.html#the-menu-element]
Allowed ARIA role attribute values:
    menu (default - do not set), directory, list, listbox, menubar, tablist, tabpanel or tree. 
Allowed ARIA state and property attributes: 
Please correct the conformance table to reflect the html5.1 spec.

**Comment by cpandhi** [comment]
Also in the HTML 5.1 spec does not clearly specify what are the valid attributes for menu type?
W3C school state 
type    can be list, toolbar or context

**Comment by cpandhi** [comment]
Sorry closed it by mistake.

**Comment by stevefaulkner** [comment]
hi @cpandhi, the normative specification in this case is ARIA in HTML. The HTML 5.2 specification information for [menu](https://w3c.github.io/html/interactive-elements.html#the-menu-element) has been updated to reflect this.

**Comment by stevefaulkner** [comment]
@cpandhi wrote:

> Also in the HTML 5.1 spec does not clearly specify what are the valid attributes for menu type?
> W3C school state
> type can be list, toolbar or context

I assume you are referring to http://www.w3schools.com/ ? which has nothing to do with the W3C and what it describes in regards to **any** web specification has no authority and is sometimes of dubious quality.

In regards to the values of the `type` attribute on the `menu` element. [in HTML 5.1 it is only `context`](https://www.w3.org/TR/html51/interactive-elements.html#attr-valuedef-menu-type-context), as this is the only value that is implemented (currently only by a  limited number of browsers)

**Comment by cpandhi** [comment]
Thanks Steve.

**Comment by stevefaulkner** [comment]
@cpandhi no problem :-)

**Comment by cpandhi** [comment]
Sorry one more clarification, for the menu element why does the [aria in html ](https://w3c.github.io/html-aria/) say attribute applicable to toolbar role?
menu type = context     role=menu   No role global aria-\* attributes and any aria-\* attributes applicable to the toolbar role.

**Comment by cpandhi** [comment]
Perfect, Thank you Steve.
