### ISSUE TITLE
DT element change to default role=term (ARIA Working Group Comment)

### ISSUE THREAD

**Issue by jongund** [w3c/html-aria#57]
Based on discussion in the ARIA working group on 12/8//2016 and 12/15/2016 we would like to see the mapping for the DT element changed from LISTITEM to TERM.

NOTE: ARIA 1.2 will address the roles TERM and DEFINITION being part of a definition list.

**Comment by stevefaulkner** [comment]
@jogund this needs to filed against https://w3c.github.io/html-aam/ this spec only reflects the implicit semantics defined in that spec.
