### ISSUE TITLE
input type=checkbox should allow role=button and role=switch

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/html-aria#6]
moved from https://github.com/webspecs/html-aria/issues/18

jnurthen commented on 4 Jun

It is very common to base toggle buttons (role=button with aria-pressed set to true/false) and role=switch on an HTML checkbox. This spec forbids this common practice and it should not.
@stevefaulkner
Owner
stevefaulkner commented on 5 Jun

@jnurthen do you have examples you can point me to of the use of checkbox as described?
@jnurthen
jnurthen commented on 5 Jun

As usual not in public space no. Sorry.

**Comment by goetsu** [comment]
can be used to produce more thing than button for exemple tab see https://css-tricks.com/functional-css-tabs-re-revisited/ or others things see https://css-tricks.com/the-checkbox-hack/

**Comment by stevefaulkner** [comment]
button role in conjunction with aria-pressed, and switch role, now allowed.

**Comment by goetsu** [comment]
Thanks @stevefaulkner
