### ISSUE TITLE
Make grid one of the implicit roles for the table element

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/html-aria#61]
The spec currently specifies `table` as the implicit role for `table`. Add `grid` as another implicit role for it.

The `th` element has both `columnheader` and `rowheader` as its implicit roles, so from that I glean it’s possible for `table` and other elements to also have multiple implicit roles.

**Comment by dylanb** [comment]
Where is this specified? Here it states otherwise https://www.w3.org/TR/html-aria/#https://www.w3.org/TR/html-aria/#index-aria-table

**Comment by stevefaulkner** [comment]
@dylanb https://www.w3.org/TR/html-aria/#table

@sideshowbarker th has 2 possible implicit roles depending on the context used.
if the first cell in a column  = columnheader
if the first cell in a row  = rowheader
there are other algorithmic factors (so above is a simplification)

A table does not have a implicit role= grid, it only has the grid role when it is explicit via role=grid.

But anyway what does your suggestion attempt to achieve?

**Comment by sideshowbarker** [comment]
> But anyway what does your suggestion attempt to achieve?

I don’t remember for sure at this point but I believe I raised this to try to help address the problem @SiTaggart described in the comment thread starting at https://github.com/validator/validator/issues/425#issuecomment-269838393

**Comment by carmacleod** [comment]
I think this issue can be closed.
In order to be an ARIA "grid", `table` element needs explicit `role="grid"`.

**Comment by scottaohara** [comment]
Agree with @carmacleod.  A `table` cannot implicitly be a grid without `role=grid` being set to it, and `table` already allows any role.

Issue #195 will take care of the implicit roles for table children if the table is given a `role=grid`
