### ISSUE TITLE
State that authors may use an explicit role=row with the tr element

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/html-aria#62]
As an alternative to https://github.com/w3c/html-aria/issues/60 refine the spec to state that authors may use an explicit `role=row` with the `tr` element—so that if they use `role=gridcell` with `td` elements, they can still conform to the requirement in the ARIA spec that elements with an explicit `role=gridcell` must be contained in or owned by an element with an explicit `row=role`.

**Comment by dylanb** [comment]
`tr` already has an implicit role of `row`, so this would not change anything

**Comment by stevefaulkner** [comment]
@sideshowbarker 

> As an alternative to #60 refine the spec to state that authors may use an explicit role=row with the tr element—so that if they use role=gridcell with td elements

there are no restrictions on what roles [`<tr>` can have](https://www.w3.org/TR/html-aria/#tr) but it 'should not' have implicit role declared. will special case.
