### ISSUE TITLE
Possible conflict with the ARIA Authoring Practices 1.1 document

### ISSUE THREAD

**Issue by matatk** [w3c/html-aria#64]
This is similar to #63 but relates to the `<section>` element's implicit role mapping.

In [section 2 of this document](https://www.w3.org/TR/html-aria/#docconformance) the table states that `<section>` maps to:

> region	

However, in the [ARIA Authoring Practices document's HTML5 Landmark elements section](https://www.w3.org/TR/wai-aria-practices-1.1/#html5-sectioning-elements), an extra condition is added; it states that `<section>` maps to:

> region when it has an accessible name using aria-labelledby or aria-label

It seems best to ensure the info is in a single place only, and link there.

**Comment by matatk** [comment]
P.S. It could be that the ARIA Authoring Practices document has a conflict here, too, as in the [HTML Accessibility API Mappings 1.0](https://www.w3.org/TR/html-aam-1.0/#html-element-role-mappings) document, for `<section>`, there is **not** a requirement for an accessible name, but there **is** a strong suggestion of it:

> Note:It is strongly recommended that user agents such as screen readers only convey the presence of, and provide navigation for section elements, when the section element has an accessible name.

So maybe this needs to be filed in the ARIA Authoring Practices document too (though again it seems by far best to have the info only in one document, to avoid DRY errors).

**Comment by stevefaulkner** [comment]
@matak section always maps to region, it is only announced by AT when it has an accessible name. Note the  ARIA Authoring Practices document is non normative.

**Comment by matatk** [comment]
Thanks; this makes sense.  Also, the [specific `region` part of the ARIA spec](https://www.w3.org/TR/wai-aria-1.1/#region) states the same; that a `region` **must** have a label and that ATs **should** expose it as a landmark region.

I feel that the demarcation between the audience for particular parts of particular spec/related docs (web author, UA developer; AT developer) perhaps could be a little clearer: my mistake seems to've been hopping around through the docs, trying to get to the definitive answer on this and other issues, but then not being aware of the intended audiences for the different docs at which I was looking.  I wonder if something as simple as colour-coding different W3C docs based on intended audience might be of help (clearly other more semantic ways would need to be thought of to go alongside that).

**Comment by ZoeBijl** [comment]
Filed a bug on APG: https://github.com/w3c/aria-practices/issues/239

**Comment by joanmarie** [comment]
@stevefaulkner: I'd like to triple check something to be sure we don't have unwanted side effects.

The [ARIA 1.1 `region` role](https://rawgit.com/w3c/aria/master/aria/aria.html#region) was modified and has several noteworthy characteristics that were not present in 1.0, namely:

* `region` subclasses the `landmark` role
* "Authors SHOULD limit use of the region role to sections containing content with a purpose that is not accurately described by one of the other landmark roles, such as `main`, `complementary`, or `navigation`."
* "Authors MUST give each element with role `region` a brief label that describes the purpose of the content in the region."

As a result, the [Core AAM maps the `region` role unconditionally to the platform role associated with landmarks](https://rawgit.com/w3c/aria/master/core-aam/core-aam.html#details-id-45).

With the above in mind, your statement that

> section always maps to region, it is only announced by AT when it has an accessible name.

Implies that every screen reader on every platform is going to have to sanity check landmarks just in case it's a `section` element that isn't named -- _unless somebody changes something somewhere_. Given what you've said in this issue, it seems to me that we should open an additional issue against the Core AAM with conditional platform mappings based on the presence or absence of a name. Do you concur, @stevefaulkner?
