### ISSUE TITLE
should aria-required be allowed on input, type=Checkbox and type=radio

### ISSUE THREAD

**Issue by jnurthen** [w3c/html-aria#67]
ARIA in HTML states that the following attributes are allowed for input type="checkbox"
> global aria-* attributes and any aria-* attributes applicable to the allowed roles

and the following for input type="radio"
> global aria-* attributes and any aria-* attributes applicable to the menuitemradio role.

This seems to not allow aria-required on checkbox and/or radio. However, HTML allows required on radio and checkbox. aria-required maps to the same thing as HTML's required attribute in accessibility APIs. Does it make any sense to disallow using aria-required on checkboxes and radio buttons?

**Comment by stevefaulkner** [comment]
@jnurthen 
> Use the aria-required attribute on any element that is allowed the required attribute in HTML5. MUST NOT be set to false if the required attribute is set. 
https://w3c.github.io/html-aria/#attr-required

**Comment by dylanb** [comment]
Semantically, it makes no sense to have a required attribute on a field that can only have unchecked and checked IF both values (unchecked and checked) are allowable. What is being required?

For a radio button grouping, the "required" attribute applies to the group and not to the individual items. It is impossible to select all the radio buttons in a group for example but it does make sense to have a grouping with no default value and expect the user to choose one value. This is equivalent to a required select with no default value.

For checkboxes, the only interpretation of required that makes sense is one where required is equivalent to saying: "thou shalt check this checkbox" (for example accepting license terms).

So this is my way of saying that aria-required makes sense on checkboxes but does not make sense on individual radio buttons.
