### ISSUE TITLE
Allow role="none" for img alt=""

### ISSUE THREAD

**Issue by dstorey** [w3c/html-aria#69]
Regarding https://github.com/validator/validator/issues/472#issuecomment-284581561 and https://github.com/w3c/html/issues/812 , in addition to presentation, role="none" should be allowed on images with alt="".

**Comment by stevefaulkner** [comment]
thanks dave, fixed https://github.com/w3c/html-aria/commit/69d851b39069c5a49132a91adc1999d02e377ae1
