### ISSUE TITLE
Shouldn't "columnheader" and "gridcell" support the "aria-colindex" property?

### ISSUE THREAD

**Issue by AlbertWiersch** [w3c/html-aria#72]
In "3. Allowed ARIA roles, states and properties", shouldn't roles "columnheader" and "gridcell" support the "aria-colindex" property? "aria-rowindex" is listed as supported but not "aria-colindex".

See the example here:
https://www.w3.org/TR/wai-aria-1.1/#aria-colcount

**Comment by stevefaulkner** [comment]
yes and has been fixed.
