### ISSUE TITLE
allow role=none on all elements which support role=presentation

### ISSUE THREAD

**Issue by jnurthen** [w3c/html-aria#78]
role=none is exactly the same as role=presentation. This doc needs to allow role=none on all elements which allow role=presentation.

article
aside
dl
embed
figcaption
fieldset
figure
footer
form
h1..h6
header
hr
li
ol
section
ul

**Comment by lemnis** [comment]
The current spec still does not allow role `none` for the ul and hr elements.

**Comment by jnurthen** [comment]
ul still does not allow role=none
