### ISSUE TITLE
Wide review

### ISSUE THREAD

**Issue by LJWatson** [w3c/html-aria#79]
APA: [complete, no issues](https://www.w3.org/WAI/APA/wiki/ARIA_in_HTML)

ARIA: [complete, no issues](https://lists.w3.org/Archives/Public/public-aria/2017Jul/0081.html)

I18n: [complete](https://github.com/w3c/i18n-activity/issues/322)
Issue #75 is editorial

Privacy: [requested 22/2/2017, no response](https://lists.w3.org/Archives/Public/public-privacy/2017JanMar/0016.html)

Security: [requested 22/2/2017, no response](https://lists.w3.org/Archives/Public/public-web-security/2017Feb/0009.html)

TAG: [complete, no issues](https://github.com/w3ctag/design-reviews/issues/156#event-1177978969)

**Comment by LJWatson** [comment]
@stevefaulkner is there anything holding us up from moving this to CR?

**Comment by ZoeBijl** [comment]
I vaguely remember that it was discussed whether the APA review could also be accepted as ARIA review. Can’t remember what we decided on though.

**Comment by LJWatson** [comment]
@SteveFaulkner which of the open issues against this spec need resolving before we can transition to CR?
