### ISSUE TITLE
Drop the “Kind of content” column from the “Allowed ARIA roles, states and properties” table

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/html-aria#88]
Please consider dropping the entire “Kind of content” column from the “Allowed ARIA roles, states and properties” table at https://w3c.github.io/html-aria/#aria-table. It’s not stating any requirements.

I think it would be better to keep the information in that table as simple as possible — and the potential extra informational benefit that column provides is outweighed by the cost of the potential confusion it can create among users (similar to the confusion caused among users by the unnecessary per-element [*“Categories”*](https://html.spec.whatwg.org/multipage/dom.html#concept-element-categories) labeling in the HTML spec).

**Comment by stevefaulkner** [comment]
@sideshowbarker have been thinking about this and while it may be confusing I think it is needed to inform checker implementers on expected restrictions:
example:
`<div role="button"></div>`
`div` elements are classed as flow content in HTML, but a `role=button` makes the `div` into interactive content.

We want to be able to restrict problematic patterns such as:
`<div role="button"><button></button></div>`
or 
`<div role="button"><span role="checkbox"></span></div>`

So I think that assigning a mapping of 'kind of content' is needed for cases such as above. 
For the `role=button` example, it is classed as "interactive content" and can contain "Flow content, but there must be no interactive content descendant." Without defining what kind of content `role=button` is how can it be inferred that the above example are not allowed?


If you have a way of doing this without the mapping I am all ears.

**Comment by sideshowbarker** [comment]
OK, I see the intent for this now, and agree it’s useful. Implementing support for it in the checker is separate thing, so I’ll go ahead and chose this issue out as a resolved
