### ISSUE TITLE
form element should have the default role of none, unless it has an accessible name

### ISSUE THREAD

**Issue by jongund** [w3c/html-aria#94]
There are a lot of empty form elements in documents and typically a form element (usually as an artifact of some javascript library) and the associated controls are already in a more useful landmark like "main" or "search".  It is unlikely that authors will know that they are creating a landmark when they add the form element to a page, the form landmark should only be used explicitly by an author by adding the role=form attribute. 

In previous discussions on the form element I believe the consensus was the default role should be "none", unless the form element has  an accessible name, in the case the form element has  accessible name the role would be "form".
  
The other allowed roles should be "form" or "search".   

I encourage you to change this before entering CR, it is the biggest issue in the spec that I would like resolved.

**Comment by stevefaulkner** [comment]
Yes, it is an issue, which has been fixed, but this is not where the mapping is defined, it is defined in the HTML AAM and what you are asking is defined appropriately there.
